var all_games = [
  {"abbr": "AHoSCT", "name": "Azi's House of Soul Crushing Towers", "link": "https://www.roblox.com/games/83360243495088/ToPD-ToNCL-Azis-House-of-Soul-Crushing-Towers"},
  {"abbr": "AToBM", "name": "Andr's Towers of Bruh Moments", "link": "https://www.roblox.com/games/11300875374/CHRISTMAS-Andrs-Towers-of-Bruh-Moments"},
  {"abbr": "AToS", "name": "Another's Towers of Stupidity", "link": "https://www.roblox.com/games/2830417603/anothers-towers"},
  {"abbr": "ATS", "name": "Amazing's Tower Supernerfs", "link": "https://www.roblox.com/games/17120699596/Amazings-Tower-Supernerfs"},
  {"abbr": "CKR", "name": "Crazy's Kaizo Regions", "link": "https://www.roblox.com/games/3103266746/Crazys-Kaizo-Regions"},
  {"abbr": "CSCD", "name": "Caleb's Soul Crushing Domain", "link": "https://www.roblox.com/games/10283991824/SCOPE-3-Calebs-Soul-Crushing-Domain"},
  {"abbr": "CTT", "name": "Community Top Towers", "link": "https://www.roblox.com/games/109970721198777/Domain-1-LETS-GO"},
  {"abbr": "DEToH", "name": "Democratically Elected Towers of Hell", "link": "https://www.roblox.com/games/116948649505593/Alpha-DEToH"},
  {"abbr": "HT", "name": "Hades Towers", "link": "https://www.roblox.com/games/121125135868314/Hades-Towers-CHRISTMAS"},
  {"abbr": "JToH", "name": "Juke's Towers of Hell", "link": "https://www.roblox.com/games/8562822414/Jukes-Towers-of-Hell"},
  {"abbr": "JXL", "name": "JToH XL", "link": "https://www.roblox.com/games/13218032675/JToH-XL"},
  {"abbr": "JXS", "name": "JToH XS Project", "link": "https://www.roblox.com/games/18358123333/JToH-XS-Project"},
  {"abbr": "JXXL", "name": "JToH XXL", "link": "https://www.roblox.com/games/17846926884/RING-1-UPDATE-3-5-4-JToH-XXL"},
  {"abbr": "KT", "name": "Kratic Tower", "link": "https://www.roblox.com/games/9218804696/Kratic-Tower"},
  {"abbr": "KToN", "name": "Kirk's Towers of Nonsense", "link": "https://www.roblox.com/games/7184682048/QoL-SECTION-3-Kirks-Towers-of-Nonsense"},
  {"abbr": "LToD", "name": "Lask's Towers of Dread", "link": "https://www.roblox.com/games/18386437234/lasks-towers-of-dread"},
  {"abbr": "MCToH", "name": "Mtrk5's Classic Towers of Hell", "link": "https://www.roblox.com/games/4732391729/NEW-TOWERS-Mtrk5s-Classic-Towers-of-Hell"},
  {"abbr": "MToH", "name": "Mal's Towers of Hell", "link": "https://www.roblox.com/games/4588307161/Discontinued-Mals-Towers-of-Hell"},
  {"abbr": "NCoH", "name": "Nox's Citadels of Hell", "link": "https://www.roblox.com/games/9237964584/Noxs-Citadels-of-Hell"},
  {"abbr": "PoM:N", "name": "Pit of Misery: Nerfed", "link": "https://www.roblox.com/games/10914322251/Pit-of-Misery-Nerfed"},
  {"abbr": "PToD", "name": "Player's Towers of Desperation", "link": "https://www.roblox.com/games/8360384036/Players-Towers-of-Desperation"},
  {"abbr": "PToH", "name": "Purist Towers of Hell", "link": "https://www.roblox.com/games/7593639579/RING-5-Purist-Towers-of-Hell"},
  {"abbr": "SMToH", "name": "Shark's Mini Towers of Hecc", "link": "https://www.roblox.com/games/16057377099/Sharks-Mini-Towers-of-Hecc"},
  {"abbr": "TBP", "name": "The Baseplate Project", "link": "https://www.roblox.com/games/15957446104/EVILPLATE-The-Baseplate-Project"},
  {"abbr": "TCT", "name": "Thai's Crazy Towers", "link": "https://www.roblox.com/games/9066198427/Thais-Crazy-Towers"},
  {"abbr": "TG", "name": "Tower Game", "link": "https://www.roblox.com/games/5976062696/tower-game"},
  {"abbr": "TWR$", "name": "Tower$", "link": "https://www.roblox.com/games/13594795843/Tower"},
  {"abbr": "ZToA", "name": "Zee's Towers of Anger", "link": "https://www.roblox.com/games/5630198391/ToCUP-Zees-Towers-of-Anger-Reborn"}
]
