all_towers = [
  {"id": 1, "abbr": "ToDT", "name": "Tower of Double Trouble", "diff": 800, "places": [["JToH", "Zone 2"]]},
  {"id": 2, "abbr": "ToDC", "name": "Tower of Difficulty Chart", "diff": 809, "places": [["JToH", "Ring 2"]]},
  {"id": 3, "abbr": "TT", "name": "Thanos Tower", "diff": 813, "places": [["JToH", "Ring 1"]]},
  {"id": 4, "abbr": "ToHA", "name": "Tower of High Adrenaline", "diff": 816, "places": [["JToH", "Ring 9"]]},
  {"id": 5, "abbr": "ToEH", "name": "Tower of Extreme Hell", "diff": 817, "places": [["JToH", "Ring 7"]]},
  {"id": 6, "abbr": "ToBT", "name": "Tower of Bent Trauma", "diff": 818, "places": [["JToH", "Ring 9"]]},
  {"id": 7, "abbr": "ToUH", "name": "Tower of Unsettling Heights", "diff": 822, "places": [["JToH", "Lost River"], ["CSCD", "Scope 1"]]},
  {"id": 8, "abbr": "ToTL", "name": "Tower of Thinning Layers", "diff": 830, "places": [["JToH", "Zone 1"]]},
  {"id": 9, "abbr": "ToIF", "name": "Tower of Inevitable Failure", "diff": 845, "places": [["JToH", "Zone 4"]]},
  {"id": 10, "abbr": "ToCA", "name": "Tower of Curved Ascent", "diff": 846, "places": [["JToH", "Ring 9"], ["TBP", "Plate 13"]]},
  {"id": 11, "abbr": "ToMB", "name": "Tower of Mind Breaking", "diff": 851, "places": [["JToH", "Forgotten Ridge"]]},
  {"id": 12, "abbr": "ToIB", "name": "Tower of Icy Blizzards", "diff": 867, "places": [["JToH", "Ring 5"]]},
  {"id": 13, "abbr": "ToHR", "name": "Tower of Hollow Reformations", "diff": 872, "places": [["JToH", "Zone 9"]]},
  {"id": 14, "abbr": "ToPZ", "name": "Tower of Polychromatic Zero", "diff": 878, "places": [["JToH", "Zone 5"]]},
  {"id": 15, "abbr": "ToRER", "name": "Tower of Rough Endoplasmic Reticulum", "diff": 882, "places": [["JToH", "Zone 8"]]},
  {"id": 16, "abbr": "ToC", "name": "Tower of Confusion", "diff": 884, "places": [["JToH", "Ring 3"]]},
  {"id": 17, "abbr": "ToFaCT", "name": "Tower of Frightening and Confusing Trials", "diff": 898, "places": [["JToH", "Ring 9"]]},
  {"id": 18, "abbr": "ToAE", "name": "Tower of Astral Eclipse", "diff": 900, "places": [["JToH", "Zone 8"]]},
  {"id": 19, "abbr": "ToPB", "name": "Tower of Panelling Barricades", "diff": 905, "places": [["JToH", "Zone 9"]]},
  {"id": 20, "abbr": "ToBK", "name": "Tower of Bloodthirsty Kenos", "diff": 912, "places": [["JToH", "Ring 9"]]},
  {"id": 21, "abbr": "ToWF", "name": "Tower of Wicked Fortress", "diff": 927, "places": [["JToH", "Ashen Towerworks"]]},
  {"id": 22, "abbr": "ToSM", "name": "Tower of Strategic Mechanics", "diff": 938, "places": [["JToH", "Ring 6"]]},
  {"id": 23, "abbr": "ToHH", "name": "Tower of Hopeless Hell", "diff": 945, "places": [["JToH", "Zone 3"]]},
  {"id": 24, "abbr": "ToTB", "name": "Tower of Terrifying Beauty", "diff": 949, "places": [["JToH", "Ring 7"]]},
  {"id": 25, "abbr": "ToSO", "name": "Tower of Suffering Outside", "diff": 954, "places": [["JToH", "Ring 8"]]},
  {"id": 26, "abbr": "ToAAA", "name": "Tower of Astronomically Aimless Annoyances", "diff": 958, "places": [["JToH", "Zone 4"]]},
  {"id": 27, "abbr": "ToTDA", "name": "Tower of The Dripping Amalgam", "diff": 961, "places": [["JToH", "Zone 6"]]},
  {"id": 28, "abbr": "ToEI", "name": "Tower of Externalizing Insanity", "diff": 994, "places": [["JToH", "Ring 8"]]},
  {"id": 29, "abbr": "ToFM", "name": "Tower of Fractured Memories", "diff": 999, "places": [["JToH", "Zone 7"]]},
  {"id": 30, "abbr": "ToIM", "name": "Tower of Impossible Movement", "diff": 1000, "places": [["JToH", "Ring 6"]]},
  {"id": 31, "abbr": "ToFN", "name": "Tower of Frightening Nightmares", "diff": 1008, "places": [["JToH", "Ring 5"]]},
  {"id": 32, "abbr": "ToMM", "name": "Tower of Micro Management", "diff": 1036, "places": [["JToH", "Zone 6"]]},
  {"id": 33, "abbr": "ToAR", "name": "Tower of Alien Radiance", "diff": 1040, "places": [["JToH", "Zone 5"]]},
  {"id": 34, "abbr": "ToNS", "name": "Tower of Nervous Sweating", "diff": 1052, "places": [["JToH", "Ring 9"]]},
  {"id": 35, "abbr": "ToUA", "name": "Tower of Uncanny Agony", "diff": 1067, "places": [["JToH", "Zone 7"]]},
  {"id": 36, "abbr": "ToWWW", "name": "Tower of Wildly Wacky Wonders", "diff": 1081, "places": [["JToH", "Zone 9"]]},
  {"id": 37, "abbr": "ToI", "name": "Tower of Inception", "diff": 1091, "places": [["JToH", "Ring 4"]]},
  {"id": 38, "abbr": "ToAM", "name": "Tower of Augmented Misery", "diff": 1100, "places": [["JToH", "Ring 9"]]},
  {"id": 39, "abbr": "ToGF", "name": "Tower of Generation Failure", "diff": 1118, "places": [["JToH", "Ring 8"]]},
  {"id": 40, "abbr": "ToEMP", "name": "Tower of Empty Meaningless Patterns", "diff": 1133, "places": [["JToH", "Zone 9"]]},
  {"id": 41, "abbr": "ToDIE", "name": "Tower of Descent Into Exile", "diff": 1142, "places": [["JToH", "Zone 8"], ["AToS", "Ring 8"]]},
  {"id": 42, "abbr": "ToCR", "name": "Tower of Champion's Road", "diff": 1171, "places": [["JToH", "Ring 9"]]},
  {"id": 43, "abbr": "ToER", "name": "Tower of Elongated Runs", "diff": 1187, "places": [["JToH", "Ring 7"]]},
  {"id": 44, "abbr": "ToCP", "name": "Tower of Cruel Punishment", "diff": 1199, "places": [["JToH", "Ring 9"]]},
  {"id": 45, "abbr": "ToXIC", "name": "Tower of Xerically Infuriating Calamity", "diff": 1002, "places": [["JToH", "Pit of Misery"]]},
  {"id": 46, "abbr": "ToOLC", "name": "Tower of Overthinking Life Choices", "diff": 1079, "places": [["JToH", "Pit of Misery"]]},
  {"id": 47, "abbr": "ToVM", "name": "Tower of Vindictive Maneuvers", "diff": 1102, "places": [["JToH", "Pit of Misery"]]},
  {"id": 48, "abbr": "ToSE", "name": "Tower of Shunning Excursion", "diff": 1166, "places": [["JToH", "Pit of Misery"]]},
  {"id": 49, "abbr": "ToVH", "name": "Tower of Vacant Hindrances", "diff": 1198, "places": [["JToH", "Pit of Misery"], ["CSCD", "Scope 1"]]},
  {"id": 50, "abbr": "ToWM", "name": "Tower of Water Melon", "diff": 1230, "places": [["JToH", "Pit of Misery"]]},
  {"id": 51, "abbr": "ToEV", "name": "Tower of Eternal Void", "diff": 1255, "places": [["JToH", "Pit of Misery"]]},
  {"id": 52, "abbr": "ToTRP", "name": "Tower of The Roof's Pique", "diff": 1260, "places": [["JToH", "Pit of Misery"], ["CSCD", "Scope 1"]]},
  {"id": 53, "abbr": "ToBF", "name": "Tower of Blind Fate", "diff": 1300, "places": [["JToH", "Pit of Misery"]]},
  {"id": 54, "abbr": "CoIV", "name": "Citadel of Infinite Void", "diff": 1323, "places": [["JToH", "Pit of Misery"]]},
  {"id": 55, "abbr": "ToSF", "name": "Tower of Spiralling Fates", "diff": 1354, "places": [["JToH", "Pit of Misery"], ["CTT", "Domain 1"]]},
  {"id": 56, "abbr": "ToDC:C", "name": "Tower of Difficulty Chart: Classic", "diff": 801, "places": [["Place", ""]], "game": "https://www.roblox.com/games/6183527403/ToDC-C-Tower-of-Difficulty-Chart-Classic"},
  {"id": 57, "abbr": "ToQA", "name": "Tower of Quaint Activations", "diff": 849, "places": [["JToH", "Time-Lost Sands"]]},
  {"id": 58, "abbr": "ToBD", "name": "Tower of Boreal Disarray", "diff": 852, "places": [["Place", ""]], "game": "https://www.roblox.com/games/8620395748/Tower-of-Boreal-Disarray"},
  {"id": 59, "abbr": "ToSTR", "name": "Tower of Slipping Through Reality", "diff": 863, "places": [["JToH", "Time-Lost Clockwork"]]},
  {"id": 60, "abbr": "BT", "name": "Baldi Tower", "diff": 870, "places": [["JToH", "April Fools 2021"]]},
  {"id": 61, "abbr": "ToUB", "name": "Tower of Unending Bamboozles", "diff": 873, "places": [["Place", ""]], "game": "https://www.roblox.com/games/16388763948/Tower-of-Unending-Bamboozles"},
  {"id": 62, "abbr": "SoGLUBIC", "name": "Steeple of Gears Locked Up Because It's Cold", "diff": 876, "places": [["JToH", "April Fools 2023"]]},
  {"id": 63, "abbr": "T1", "name": "Tower 1", "diff": 913, "places": [["JToH", "April Fools 2024"]]},
  {"id": 64, "abbr": "ToDB", "name": "Tower of Da Baby", "diff": 1085, "places": [["JToH", "April Fools 2021"]]},
  {"id": 65, "abbr": "ToRM", "name": "Tower of Reddish Monolith", "diff": 800, "places": [["CSCD", "Scope 1"]]},
  {"id": 66, "abbr": "ToMO", "name": "Tower of Minimal Obstacles", "diff": 859, "places": [["CSCD", "Scope 2"]]},
  {"id": 67, "abbr": "ToII", "name": "Tower of Increasing Intensity", "diff": 866, "places": [["CSCD", "Scope 2"]]},
  {"id": 68, "abbr": "ToTTO", "name": "Tower of Two To One", "diff": 878, "places": [["CSCD", "Scope 1"]]},
  {"id": 69, "abbr": "ToHR", "name": "Tower of Hellish Rouge", "diff": 880, "places": [["CSCD", "Scope 3"]]},
  {"id": 70, "abbr": "ToDB", "name": "Tower of Difficulty Breezing", "diff": 815, "places": [["CSCD", "Scope 2"]]},
  {"id": 71, "abbr": "ToBI", "name": "Tower of Baleful Impedes", "diff": 896, "places": [["CSCD", "Scope 3"]]},
  {"id": 72, "abbr": "ToCG", "name": "Tower of Clean Glass", "diff": 911, "places": [["CSCD", "Scope 1"]]},
  {"id": 73, "abbr": "ToAW", "name": "Tower of Abysmal Wrath", "diff": 919, "places": [["CSCD", "Scope 3"]]},
  {"id": 74, "abbr": "ToCaL", "name": "Tower of Circuits and Lasers", "diff": 956, "places": [["CSCD", "Scope 1"]]},
  {"id": 75, "abbr": "ToUG", "name": "Tower of Underlying Grief", "diff": 959, "places": [["CSCD", "Scope 1"]]},
  {"id": 76, "abbr": "ToRC", "name": "Tower of Raspy Cascades", "diff": 952, "places": [["CSCD", "Scope 3"]]},
  {"id": 77, "abbr": "ToUA", "name": "Tower of Uttermost Antagonism", "diff": 974, "places": [["CSCD", "Scope 2"], ["AToS", "Realm 2"]]},
  {"id": 78, "abbr": "ToTFW", "name": "Tower of THE FOREBODING WALL", "diff": 977, "places": [["CSCD", "Scope 3"]]},
  {"id": 79, "abbr": "ToSR", "name": "Tower of Shattered Resolve", "diff": 989, "places": [["CSCD", "Scope 2"]]},
  {"id": 80, "abbr": "ToLE", "name": "Tower of Lunar Expansion", "diff": 993, "places": [["CSCD", "Scope 2"]]},
  {"id": 81, "abbr": "ToPB:C", "name": "Tower of Panelling Barricades: Classic", "diff": 997, "places": [["CSCD", "Scope 3"]]},
  {"id": 82, "abbr": "ToIP", "name": "Tower of Intricate Precision", "diff": 1006, "places": [["CSCD", "Scope 1"]]},
  {"id": 83, "abbr": "ToCM", "name": "Tower of Cliffside Madness", "diff": 1022, "places": [["CSCD", "Scope 1"], ["AToS", "Ring 8"]]},
  {"id": 84, "abbr": "ToID", "name": "Tower of Insensible Distress", "diff": 1030, "places": [["CSCD", "Scope 3"], ["TCT", "Ring 4"]]},
  {"id": 85, "abbr": "ToTSM", "name": "Tower of Two Sided Misery", "diff": 1037, "places": [["CSCD", "Scope 2"]]},
  {"id": 86, "abbr": "ToAD", "name": "Tower of Agonizing Demise", "diff": 1049, "places": [["CSCD", "Scope 2"], ["MToH", "Place 5"]]},
  {"id": 87, "abbr": "ToLT", "name": "Tower of Lavish Thrones", "diff": 1056, "places": [["CSCD", "Scope 2"]]},
  {"id": 88, "abbr": "ToWV", "name": "Tower of Wayward Venture", "diff": 1071, "places": [["CSCD", "Scope 3"], ["CTT", "Domain 1"]]},
  {"id": 89, "abbr": "ToMA", "name": "Tower of Mauve Attestations", "diff": 1085, "places": [["CSCD", "Scope 3"]]},
  {"id": 90, "abbr": "ToIG", "name": "Tower of Inferno Galore", "diff": 1103, "places": [["CSCD", "Scope 1"]]},
  {"id": 91, "abbr": "ToG", "name": "Tower of Gelidity", "diff": 1109, "places": [["CSCD", "Scope 2"]]},
  {"id": 92, "abbr": "ToRRA", "name": "Tower of Ruthless Royal Architecture", "diff": 1114, "places": [["CSCD", "Scope 1"]]},
  {"id": 93, "abbr": "ToTM", "name": "Tower of Thin Mints", "diff": 1172, "places": [["JToH", "The Eternal Abyss"], ["CSCD", "Scope 3"]]},
  {"id": 94, "abbr": "ToU", "name": "Tower of Unorthodoxy", "diff": 1142, "places": [["CSCD", "Scope 3"]]},
  {"id": 95, "abbr": "ToNI", "name": "Tower of Necrotic Incantation", "diff": 1150, "places": [["CSCD", "Scope 2"]]},
  {"id": 96, "abbr": "STONE", "name": "S.T.O.N.E Facility", "diff": 1159, "places": [["CSCD", "Scope 2"]]},
  {"id": 97, "abbr": "ToPA", "name": "Tower of Pulsating Ambitions", "diff": 1165, "places": [["CSCD", "Scope 1"]]},
  {"id": 98, "abbr": "ToJ", "name": "Tower of Jocundigluey", "diff": 1173, "places": [["CSCD", "Scope 3"], ["CTT", "Domain 1"]]},
  {"id": 99, "abbr": "ToJJ", "name": "Tower of Jabberwock Jagger", "diff": 1200, "places": [["CSCD", "Scope 3"], ["CTT", "Domain 1"]]},
  {"id": 100, "abbr": "ToTW", "name": "Tower of Thje Wall", "diff": 1213, "places": [["JToH", "The Eternal Abyss"], ["CSCD", "Scope 3"]]},
  {"id": 101, "abbr": "ToFP", "name": "Tower of Futile Perusal", "diff": 1238, "places": [["CSCD", "Scope 2"], ["TBP", "Plate 11"]]},
  {"id": 102, "abbr": "ToLP", "name": "Tower of Lucas Penteado", "diff": 1263, "places": [["CSCD", "Scope 1"]]},
  {"id": 103, "abbr": "CoTEC", "name": "Citadel of The Eternal Calamity", "diff": 1312, "places": [["JToH", "The Eternal Abyss"], ["CSCD", "Scope 1"]]},
  {"id": 104, "abbr": "SoJoL", "name": "Steeple of Jack o' Lament", "diff": 831, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11004999814"},
  {"id": 105, "abbr": "SoPS", "name": "Steeple of Present Stairs", "diff": 847, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11702697136"},
  {"id": 106, "abbr": "SoUR", "name": "Steeple of Unwrapping Rituals", "diff": 850, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11497936961"},
  {"id": 107, "abbr": "SoWW", "name": "Steeple of Wandering Willow", "diff": 869, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11150002574"},
  {"id": 108, "abbr": "SoFF", "name": "Steeple of Fervent Festivities", "diff": 883, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11446289016/"},
  {"id": 109, "abbr": "ToFA", "name": "Tower of Festive Affairs", "diff": 928, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11506957882"},
  {"id": 110, "abbr": "ToC4", "name": "Tower of Cata4", "diff": 1126, "places": [["Place", ""]], "game": "https://www.roblox.com/games/9053906493"},
  {"id": 111, "abbr": "SoTG", "name": "Steeple of Treacherous Gnomery", "diff": 801, "places": [["AToS", "Ring 3"]]},
  {"id": 112, "abbr": "ToTU", "name": "Tower of Throttling Up", "diff": 811, "places": [["AToS", "Ring 2"]]},
  {"id": 113, "abbr": "ToMM", "name": "Tower of Medial Mayhem", "diff": 821, "places": [["AToS", "Realm 1"]]},
  {"id": 114, "abbr": "ToZ", "name": "Tower of Zigzagging", "diff": 829, "places": [["AToS", "Ring 1"]]},
  {"id": 115, "abbr": "ToLN", "name": "Tower of Loud Nine", "diff": 833, "places": [["AToS", "Realm 3"]]},
  {"id": 116, "abbr": "ToUC", "name": "Tower of Umbratic Complexity", "diff": 843, "places": [["AToS", "Ring 8"]]},
  {"id": 117, "abbr": "ToVP", "name": "Tower of Vague Perceptions", "diff": 856, "places": [["AToS", "Ring 6"]]},
  {"id": 118, "abbr": "ToCT", "name": "Tower of Contrasting Themes", "diff": 860, "places": [["AToS", "Ring 5"]]},
  {"id": 119, "abbr": "ToCP", "name": "Tower of Cruel Punishments", "diff": 874, "places": [["AToS", "Ring 3"], ["MCToH", "World 1"]]},
  {"id": 120, "abbr": "ToC", "name": "Tower of Cognition", "diff": 888, "places": [["AToS", "Ring 4"]]},
  {"id": 121, "abbr": "ToFR", "name": "Tower of Futile Retribution", "diff": 891, "places": [["AToS", "Ring 8"]]},
  {"id": 122, "abbr": "ToNT", "name": "Tower of Nice Tasks", "diff": 894, "places": [["AToS", "Realm 4"]]},
  {"id": 123, "abbr": "ToTHT", "name": "Tower of Tee Hee Time", "diff": 899, "places": [["AToS", "Realm 4"]]},
  {"id": 124, "abbr": "ToPT", "name": "Tower of Perplexity Tabulation", "diff": 900, "places": [["AToS", "Ring 8"]]},
  {"id": 125, "abbr": "ToKT", "name": "Tower of Kyoi Tekina", "diff": 915, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 126, "abbr": "SoAD", "name": "Steeple of A Down", "diff": 920, "places": [["AToS", "Ring 4"]]},
  {"id": 127, "abbr": "ToDPA", "name": "Tower of Dangerous Pillar Adventuring", "diff": 937, "places": [["AToS", "Ring 7"]]},
  {"id": 128, "abbr": "ToPD", "name": "Tower of Pure Dopamine", "diff": 948, "places": [["AToS", "Realm 3"]]},
  {"id": 129, "abbr": "ToDED", "name": "Tower of Deep End Displeasure", "diff": 955, "places": [["AToS", "Ring 8"]]},
  {"id": 130, "abbr": "ToEA:C", "name": "Tower of Excruciating Anguish: Classic", "diff": 959, "places": [["AToS", "Ring 5"]]},
  {"id": 131, "abbr": "ToPH", "name": "Tower of Parallel Heights", "diff": 972, "places": [["AToS", "Ring 3"]]},
  {"id": 132, "abbr": "ToLA", "name": "Tower of Lus Abutendi", "diff": 976, "places": [["AToS", "Realm 4"]]},
  {"id": 133, "abbr": "ToIS", "name": "Tower of Infuriating Supplement", "diff": 991, "places": [["AToS", "Ring 8"]]},
  {"id": 134, "abbr": "ToSD", "name": "Tower of Sempiternal Disquietude", "diff": 1016, "places": [["AToS", "Ring 8"]]},
  {"id": 135, "abbr": "ToEB", "name": "Tower of Extravagant Borders", "diff": 1062, "places": [["AToS", "Ring 6"]]},
  {"id": 136, "abbr": "ToS", "name": "Tower of Seclusion", "diff": 1079, "places": [["AToS", "Ring 8"]]},
  {"id": 137, "abbr": "ToCR", "name": "Tower of Chacina Repentina", "diff": 1080, "places": [["AToS", "Ring 7"]]},
  {"id": 138, "abbr": "ToCL", "name": "Tower of Cataclysmic Layers", "diff": 1089, "places": [["AToS", "Ring 7"]]},
  {"id": 139, "abbr": "ToCI", "name": "Tower of Chromatic Inclination", "diff": 1099, "places": [["AToS", "Realm 4"], ["CTT", "Domain 1"]]},
  {"id": 140, "abbr": "ToRC", "name": "Tower of Rove Culmination", "diff": 1124, "places": [["AToS", "Ring 8"]]},
  {"id": 141, "abbr": "ToVS", "name": "Tower of Virulent Sojourn", "diff": 1196, "places": [["AToS", "Ring 8"], ["CTT", "Domain 1"]]},
  {"id": 142, "abbr": "ToABT", "name": "Tower of A Bad Time", "diff": 834, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 143, "abbr": "ToEF", "name": "Tower of Eternal Freezing", "diff": 838, "places": [["AToS", "Sword Fight Canyon"], ["MToH", "Place 5"]]},
  {"id": 144, "abbr": "ToCT", "name": "Tower of Chair Throwing", "diff": 855, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 145, "abbr": "CoVD", "name": "Citadel of Varying Difficulties", "diff": 871, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 146, "abbr": "ToSaP", "name": "Tower of Skill and Patience", "diff": 923, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 147, "abbr": "ToCaIG", "name": "Tower of Complex and Idiotic Gameplay", "diff": 986, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 148, "abbr": "ToSC", "name": "Tower of Swift Chacine", "diff": 1048, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 149, "abbr": "ToEO", "name": "Tower of Exodus Obscurity", "diff": 1182, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 150, "abbr": "ToFB", "name": "Tower of Five Below", "diff": 852, "places": [["AToS", "April Fools 2023"]]},
  {"id": 151, "abbr": "ToPL", "name": "Tower of Pestiferous Line", "diff": 907, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 152, "abbr": "ToWS", "name": "Tower of Wet Socks", "diff": 949, "places": [["AToS", "April Fools 2023"]]},
  {"id": 153, "abbr": "ToDND", "name": "Tower of Doltish Ninny Dunce", "diff": 955, "places": [["AToS", "April Fools 2022"]]},
  {"id": 154, "abbr": "ToUM", "name": "Tower of Umrah Market", "diff": 1047, "places": [["AToS", "April Fools 2023"]]},
  {"id": 155, "abbr": "OoTS", "name": "Obelisk of True Skill", "diff": 814, "places": [["JXXL", "Ring 1"]]},
  {"id": 156, "abbr": "OoWS", "name": "Obelisk of Wacky Strategy", "diff": 884, "places": [["JXL", "Ring 2"]]},
  {"id": 157, "abbr": "CoIT", "name": "Citadel of Indeterminate Turf", "diff": 857, "places": [["JXL", "Ring 4"]]},
  {"id": 158, "abbr": "CoTL", "name": "Citadel of Thinning Layers", "diff": 865, "places": [["JXL", "Zone 1"]]},
  {"id": 159, "abbr": "GCoLS", "name": "Great Citadel of Laptop Splitting", "diff": 879, "places": [["JXXL", "Ring 1"]]},
  {"id": 160, "abbr": "OoP", "name": "Obelisk of Peril", "diff": 886, "places": [["JXL", "Zone 1"]]},
  {"id": 161, "abbr": "TC", "name": "Thanos Citadel", "diff": 892, "places": [["JXL", "Ring 1"]]},
  {"id": 162, "abbr": "CoMB", "name": "Citadel of Mind Breaking", "diff": 896, "places": [["JXL", "Forgotten Ridge"]]},
  {"id": 163, "abbr": "CoDC", "name": "Citadel of Difficulty Chart", "diff": 943, "places": [["JXL", "Ring 2"]]},
  {"id": 164, "abbr": "CoUC", "name": "Citadel of Utter Confusion", "diff": 985, "places": [["JXL", "Ring 3"]]},
  {"id": 165, "abbr": "SCONE", "name": "S.C.O.N.E Facility", "diff": 1095, "places": [["JXL", "Ring 4"]]},
  {"id": 166, "abbr": "CoI", "name": "Citadel of Inception", "diff": 1111, "places": [["JXL", "Ring 4"]]},
  {"id": 167, "abbr": "ToRD", "name": "Tower of Ruptured Division", "diff": 895, "places": [["Place", ""]], "game": "https://www.roblox.com/games/9651122175/Tower-of-Ruptured-Division"},
  {"id": 168, "abbr": "SoJY", "name": "Steeple of Joon Yorigami", "diff": 944, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15131275415/Steeple-of-Joon-Yorigami"},
  {"id": 169, "abbr": "ToCA", "name": "Tower of Converged Agitation", "diff": 971, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10599450002/Tower-of-Converged-Agitation"},
  {"id": 170, "abbr": "ToCF", "name": "Tower of Creature Feature", "diff": 990, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15507815305/Tower-of-Creature-Feature"},
  {"id": 171, "abbr": "ToPT", "name": "Tower of Pure Torment", "diff": 932, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 172, "abbr": "ToEtA", "name": "Tower of Ease to Abyss", "diff": 968, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 173, "abbr": "ToEA", "name": "Tower of Excruciating Anguish", "diff": 1029, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 174, "abbr": "ToHN", "name": "Tower of Hellish Nightmares", "diff": 1062, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 175, "abbr": "ToUP", "name": "Tower of Unrelenting Precipice", "diff": 1087, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 176, "abbr": "ToQ", "name": "Tower of Quadrilaterals", "diff": 1096, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 177, "abbr": "ToOE", "name": "Tower of Otherworldly Expertise", "diff": 1108, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 178, "abbr": "ToTO", "name": "Tower of Tortuous Oblivion", "diff": 1139, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 179, "abbr": "ToC", "name": "Tower of Centchade", "diff": 1148, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 180, "abbr": "ToHG", "name": "Tower of Heaven's Gate", "diff": 1177, "places": [["JToH", "The Eternal Abyss"], ["CTT", "Domain 1"]]},
  {"id": 181, "abbr": "ToMN", "name": "Tower of Malefic Nuisances", "diff": 1233, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 182, "abbr": "SoD", "name": "Steeple of Daze", "diff": 1227, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 183, "abbr": "ToTSTL", "name": "Tower of The Sky's The Limit", "diff": 1236, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 184, "abbr": "ToFA", "name": "Tower of Flagrant Aggravation", "diff": 1244, "places": [["JToH", "The Eternal Abyss"], ["CTT", "Domain 1"]]},
  {"id": 185, "abbr": "ToQD", "name": "Tower of Quite Devious", "diff": 1251, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 186, "abbr": "ToIR", "name": "Tower of Irritating Results", "diff": 809, "places": [["TCT", "Timeless Archipelago"]]},
  {"id": 187, "abbr": "ToFoH", "name": "Tower of Fear of Heights", "diff": 821, "places": [["TCT", "Ring 4"]]},
  {"id": 188, "abbr": "CoR", "name": "Citadel of Rampancy", "diff": 824, "places": [["TCT", "Ring 4"]]},
  {"id": 189, "abbr": "ToTC", "name": "Tower of Tilt Controls", "diff": 836, "places": [["TCT", "Ring 2"]]},
  {"id": 190, "abbr": "SoSES", "name": "Steeple of Side Eye Scaling", "diff": 850, "places": [["TCT", "Sunset Farlands"]]},
  {"id": 191, "abbr": "ToHR:C", "name": "Tower of Hellish Rouge: Classic", "diff": 876, "places": [["TCT", "Ring 1"]]},
  {"id": 192, "abbr": "ToSD", "name": "Tower of Sitting Down", "diff": 897, "places": [["TCT", "Ring 3"]]},
  {"id": 193, "abbr": "ToGG", "name": "Tower of Googoo Gaagaa", "diff": 948, "places": [["TCT", "Ring 3"]]},
  {"id": 194, "abbr": "ToNA", "name": "Tower of Neverending Agony", "diff": 985, "places": [["TCT", "Ring 4"]]},
  {"id": 195, "abbr": "ToNR", "name": "Tower of Negative Reinforcement", "diff": 992, "places": [["TCT", "Timeless Archipelago"]]},
  {"id": 196, "abbr": "CoLD", "name": "Citadel of Love Death", "diff": 817, "places": [["NCoH", "Ring 2"]]},
  {"id": 197, "abbr": "CoUC", "name": "Citadel of Upended Chromatism", "diff": 832, "places": [["NCoH", "Ring 1"]]},
  {"id": 198, "abbr": "CoHSR", "name": "Citadel of High Sky Rise", "diff": 886, "places": [["NCoH", "Ring 1"]]},
  {"id": 199, "abbr": "ToTDS", "name": "Tower of The DiCaprio Story", "diff": 906, "places": [["Place", ""]], "game": "https://www.roblox.com/games/13222620808/Tower-of-The-DiCaprio-Story"},
  {"id": 200, "abbr": "ToHE", "name": "Tower of Hotel Exploration", "diff": 1034, "places": [["Place", ""]], "game": "https://www.roblox.com/games/8714551508/Tower-of-Hotel-Exploration"},
  {"id": 201, "abbr": "CoS", "name": "Citadel of Subway", "diff": 825, "places": [["NCoH", "Ring 3"]]},
  {"id": 202, "abbr": "CoCCC", "name": "Citadel of Condescendingly Convulsive Climbing", "diff": 946, "places": [["NCoH", "Ring 3"]]},
  {"id": 203, "abbr": "ToP", "name": "Tower of Persistence", "diff": 804, "places": [["TWR$", "Ring 3"]]},
  {"id": 204, "abbr": "ToBP", "name": "Tower of Big Pain", "diff": 827, "places": [["TWR$", "Ring 2"]]},
  {"id": 205, "abbr": "ToCT", "name": "Tower of Carpal Tunnels", "diff": 885, "places": [["TWR$", "Ring 1"]]},
  {"id": 206, "abbr": "ToBS", "name": "Tower of Both Sides", "diff": 902, "places": [["TWR$", "Ring 2"]]},
  {"id": 207, "abbr": "TT", "name": "Thor Tower", "diff": 924, "places": [["TWR$", "Ring 3"]]},
  {"id": 208, "abbr": "ToS", "name": "Tower of Silver", "diff": 979, "places": [["TWR$", "Ring 2.5"]]},
  {"id": 209, "abbr": "ToIC", "name": "Tower of Imminent Control", "diff": 806, "places": [["KToN", "Section 2"]]},
  {"id": 210, "abbr": "ToFP", "name": "Tower of Fabled Passage", "diff": 810, "places": [["KToN", "Section 1"]]},
  {"id": 211, "abbr": "ToKR", "name": "Tower of Kutsen Rouge", "diff": 846, "places": [["KToN", "Section 3"]]},
  {"id": 212, "abbr": "ToPE", "name": "Tower of Plaque Etiquette", "diff": 909, "places": [["KToN", "Section 2"]]},
  {"id": 213, "abbr": "ToPG", "name": "Tower of Prolific Gardens", "diff": 975, "places": [["KToN", "Section 3"]]},
  {"id": 214, "abbr": "ToTW:SN", "name": "Tower of Thje Wall: Super Nerf", "diff": 808, "places": [["ATS", "Ring 3"]]},
  {"id": 215, "abbr": "ToTWV:SN", "name": "Tower of The Wedge's Vengeance: Super Nerf", "diff": 815, "places": [["ATS", "Ring 2"]]},
  {"id": 216, "abbr": "ToOE:SN", "name": "Tower of Otherworldly Expertise: Super Nerf", "diff": 820, "places": [["ATS", "Ring 3"]]},
  {"id": 217, "abbr": "ToVS:SN", "name": "Tower of Virulent Sojourn: Super Nerf", "diff": 832, "places": [["ATS", "Ring 2"]]},
  {"id": 218, "abbr": "ToEV:SN", "name": "Tower of Eternal Void: Super Nerf", "diff": 834, "places": [["ATS", "Ring 1"]]},
  {"id": 219, "abbr": "ToWM:SN", "name": "Tower of Water Melon: Super Nerf", "diff": 837, "places": [["ATS", "Ring 1"]]},
  {"id": 220, "abbr": "ToFP:SN", "name": "Tower of Futile Perusal: Super Nerf", "diff": 854, "places": [["ATS", "Ring 1"]]},
  {"id": 221, "abbr": "STONE:SN", "name": "S.T.O.N.E Facility: Super Nerf", "diff": 864, "places": [["ATS", "Ring 2"]]},
  {"id": 222, "abbr": "ToCL:SN", "name": "Tower of Cataclysmic Layers: Super Nerf", "diff": 865, "places": [["ATS", "Ring 1"]]},
  {"id": 223, "abbr": "ToSM", "name": "Tower of Scintillating Microscale", "diff": 866, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10059770223/Tower-of-Scintillating-Microscale"},
  {"id": 224, "abbr": "ToUC:SN", "name": "Tower of Un Ca: Super Nerf", "diff": 875, "places": [["ATS", "Ring 3"]]},
  {"id": 225, "abbr": "ToMN:SN", "name": "Tower of Malefic Nuisances: Super Nerf", "diff": 887, "places": [["ATS", "Ring 3"]]},
  {"id": 226, "abbr": "IT:SN", "name": "Ikea Tower: Super Nerf", "diff": 889, "places": [["ATS", "Ring 1"]]},
  {"id": 227, "abbr": "ToSR:SN", "name": "Tower of Spiritual Rise: Super Nerf", "diff": 890, "places": [["ATS", "Ring 1"]]},
  {"id": 228, "abbr": "ToCP:SN", "name": "Tower of Cruel Punishment: Super Nerf", "diff": 894, "places": [["ATS", "Ring 3"]]},
  {"id": 229, "abbr": "ToP:SN", "name": "Tower of Paradise: Super Nerf", "diff": 926, "places": [["ATS", "Ring 2"]]},
  {"id": 230, "abbr": "ToBF:SN", "name": "Tower of Blind Fate: Super Nerf", "diff": 930, "places": [["ATS", "Ring 1"]]},
  {"id": 231, "abbr": "ToSA:SN", "name": "Tower of Spatial Awareness: Super Nerf", "diff": 947, "places": [["ATS", "Ring 3"]]},
  {"id": 232, "abbr": "ToQU:SN", "name": "Tower of Qwerty Uiop: Super Nerf", "diff": 974, "places": [["ATS", "Ring 2"]]},
  {"id": 233, "abbr": "CoTEC:SN", "name": "Citadel of The Eternal Calamity: Super Nerf", "diff": 1003, "places": [["ATS", "Ring 1"]]},
  {"id": 234, "abbr": "ToSF:SN", "name": "Tower of Spiralling Fates: Super Nerf", "diff": 1043, "places": [["ATS", "Ring 1"]]},
  {"id": 235, "abbr": "ToSaFT", "name": "Tower of Short and Fatal Trouble", "diff": 1046, "places": [["Place", ""]], "game": "https://www.roblox.com/games/13781276177/Tower-of-Short-and-Fatal-Trouble-TTT"},
  {"id": 236, "abbr": "ToTC", "name": "Tower of Thje Corner", "diff": 1059, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11964777492/tower-of-thje-corner"},
  {"id": 237, "abbr": "ToUC", "name": "Tower of Un Ca", "diff": 1144, "places": [["Place", ""]], "game": "https://www.roblox.com/games/9454260129/Tower-of-Un-Ca"},
  {"id": 238, "abbr": "ToTDTHL:SN", "name": "Tower of The Drive Towards Human Limits: Super Nerf", "diff": 1152, "places": [["ATS", "Ring 3"]]},
  {"id": 239, "abbr": "ToTWV", "name": "Tower of The Wedge's Vengeance", "diff": 1168, "places": [["Place", "Ring 3"]], "game": "https://www.roblox.com/games/10196698433/Tower-of-The-Wedges-Vengeance"},
  {"id": 240, "abbr": "ToSA", "name": "Tower of Spatial Awareness", "diff": 1245, "places": [["CTT", "Domain 1"]]},
  {"id": 241, "abbr": "SoCB", "name": "Steeple of Cheese Burger", "diff": 1257, "places": [["JToH", "Pit of Misery"]]},
  {"id": 242, "abbr": "SoNB", "name": "Steeple of Nilly Bob", "diff": 1262, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 243, "abbr": "ToSR", "name": "Tower of Spiritual Rise", "diff": 1272, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 244, "abbr": "IT", "name": "Ikea Tower", "diff": 1307, "places": [["Place", ""]], "game": "https://www.roblox.com/games/17379816541/Sweden-Tower"},
  {"id": 245, "abbr": "WHT", "name": "Worlds Hardest Tower", "diff": 1007, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11561092817/Worlds-Hardest-Tower"},
  {"id": 246, "abbr": "ToRH", "name": "Tower of Raw Hotdog", "diff": 1009, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7576926901/the-hotdog-collection"},
  {"id": 247, "abbr": "ToAF", "name": "Tower of Anarchist Fantasies", "diff": 994, "places": [["Place", ""]], "game": "https://www.roblox.com/games/9808788974/Tower-of-Anarchist-Fantasies#!/game-instances"},
  {"id": 248, "abbr": "ToPP", "name": "Tower of Painful Poling", "diff": 998, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10806596789/when-the-pole"},
  {"id": 249, "abbr": "ToPR", "name": "Tower of Painful Rememberance", "diff": 979, "places": [["ZToA", "Ring 3"]], "game": "https://www.roblox.com/games/6069627819/Tower-of-Painful-Remembrance"},
  {"id": 250, "abbr": "ToSC", "name": "Tower of Scattered Challenges", "diff": 1019, "places": [["Place", ""]], "game": "https://www.roblox.com/games/12194792902/Tower-of-Scattered-Challenges-Itemless"},
  {"id": 251, "abbr": "ToID", "name": "Tower of Indefinite Darkness", "diff": 1022, "places": [["Place", ""]], "game": "https://www.roblox.com/games/4899600584/Tower-of-Indefinite-Darkness"},
  {"id": 252, "abbr": "ToTLT", "name": "Tower of Two Layered Terror", "diff": 981, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15172639224/Tower-of-Two-Layered-Terror"},
  {"id": 253, "abbr": "ToAA", "name": "Tower of Architectural Agony", "diff": 1029, "places": [["Place", ""]], "game": "https://www.roblox.com/games/13419081799/ToAA-ToAL"},
  {"id": 254, "abbr": "ToSaPP", "name": "Tower of Specific and Precise Positioning", "diff": 1015, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11935897006/tower-of-specific-and-precise-positioning"},
  {"id": 255, "abbr": "ToMEN", "name": "Tower of Melodramatic Esoteric Nebulosity", "diff": 1031, "places": [["Place", ""]], "game": "https://www.roblox.com/games/12951065800/ToMEN"},
  {"id": 256, "abbr": "ToQQ", "name": "Tower of Quantum Quadrivium", "diff": 1033, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 257, "abbr": "ToIH", "name": "Tower of Itetsuku Hoshi", "diff": 1012, "places": [["Place", ""]], "game": "https://www.roblox.com/games/5947459409/toih"},
  {"id": 258, "abbr": "ToAG", "name": "Tower of Atomical Geometry", "diff": 1045, "places": [["Place", ""]], "game": "https://www.roblox.com/games/8881431098/Tower-of-Atomical-Geometry"},
  {"id": 259, "abbr": "ToTMS", "name": "Tower of The Mewing Sigma", "diff": 1046, "places": [["Place", ""]], "game": "https://www.roblox.com/games/16709893629/Tower-of-the-Mewing-Sigma"},
  {"id": 260, "abbr": "ToPPP", "name": "Tower of Precariously Positioned Platforms", "diff": 1070, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10275687443/Tower-of-Precariously-Positioned-Platforms#!/about"},
  {"id": 261, "abbr": "ToHaHA", "name": "Tower of Hitbox and Health Abuse", "diff": 1061, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10066307934/Tower-of-Hitbox-and-Health-Abuse-Reborn"},
  {"id": 262, "abbr": "ToPP", "name": "Tower of Punishing Paroxysm", "diff": 1047, "places": [["Place", ""]], "game": "https://www.roblox.com/games/14981138060/ToPP-cscd#!/game-instances"},
  {"id": 263, "abbr": "SoWO", "name": "Steeple of Wacky Obstructions", "diff": 1050, "places": [["Place", ""]], "game": "https://www.roblox.com/games/14711169611/Steeple-of-wacky-obstructions"},
  {"id": 264, "abbr": "ToD", "name": "Tower of Duality", "diff": 1056, "places": [["TG", "Zone 4"]]},
  {"id": 265, "abbr": "ToEP", "name": "Tower of Ethereal Punishment", "diff": 1065, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7416416909/Tower-of-Etherial-Punishment"},
  {"id": 266, "abbr": "ToCCC", "name": "Tower of Colossal Crossroad Climbing", "diff": 1066, "places": [["CTT", "Domain 1"]]},
  {"id": 267, "abbr": "ToBM", "name": "Tower of Brisk Movement", "diff": 1071, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15280041135/Tower-of-Brisk-Movement"},
  {"id": 268, "abbr": "ToDP", "name": "Tower of Dynamic Pulse", "diff": 1041, "places": [["CTT", "Domain 1"]]},
  {"id": 269, "abbr": "ToRI", "name": "Tower of Reflecting Impediments", "diff": 1073, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15496896527/Tower-of-Reflecting-Impediments#!/game-instances"},
  {"id": 270, "abbr": "ToRRR", "name": "Tower of Roughly Rotated Ruin", "diff": 1075, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7676098737/tower-of-roughly-rotated-ruin-redone"},
  {"id": 271, "abbr": "ToTOB", "name": "Tower of The Opp Block", "diff": 1087, "places": [["HT", "Ring 1"]]},
  {"id": 272, "abbr": "ToID", "name": "Tower of Interstellar Division", "diff": 1093, "places": [["Place", ""]], "game": "https://www.roblox.com/games/9601383628/tower-of-interstellar-division"},
  {"id": 273, "abbr": "ToHC", "name": "Tower of Hoarse Constraints", "diff": 1034, "places": [["Place", ""]], "game": "https://www.roblox.com/games/12638736665/Tower-of-Hoarse-Constraints"},
  {"id": 274, "abbr": "ToQM", "name": "Tower of Quantum Mentality", "diff": 1081, "places": [["ZToA", "Regret's Cave"]]},
  {"id": 275, "abbr": "ToDP", "name": "Tower of Destructive Peril", "diff": 1083, "places": [["TBP", "Plate 10"]]},
  {"id": 276, "abbr": "ToNI", "name": "Tower of Narrow Intensification", "diff": 1094, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15293301930/Tower-of-Narrow-Intensification"},
  {"id": 277, "abbr": "ToHI", "name": "Tower of Heinous Interference", "diff": 1085, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7260155319/Tower-of-Heinous-Interference"},
  {"id": 278, "abbr": "ToFT", "name": "Tower of Flummin' Time", "diff": 1090, "places": [["HT", "Ring 1"]]},
  {"id": 279, "abbr": "ToCS", "name": "Tower of Circuitous Spiral", "diff": 1078, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10913079814/Tower-of-Circuitous-Spiral"},
  {"id": 280, "abbr": "ToRI", "name": "Tower of Radioactive Inclusions", "diff": 1059, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15496896527/Tower-of-Reflecting-Impediments#!/game-instances"},
  {"id": 281, "abbr": "ToHaD", "name": "Tower of Hell and Despair", "diff": 1078, "places": [["Place", ""]], "game": "https://www.roblox.com/games/5549397467/ring-2000#!/game-instances"},
  {"id": 282, "abbr": "ToCUP", "name": "Tower of Cruel Underestimated Parkour", "diff": 1090, "places": [["ZToA", "Regret's Cave"], ["CTT", "Domain 1"]]},
  {"id": 283, "abbr": "ToPT", "name": "Tower of Precise Turns", "diff": 1114, "places": [["Place", ""]], "game": "https://roblox.com/games/10260790188/tower-of-precise-turns"},
  {"id": 284, "abbr": "ToYH", "name": "Tower of Yummy Hotdog", "diff": 1095, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7576926901/the-hotdog-collection"},
  {"id": 285, "abbr": "ToATC", "name": "Tower of Atrocious Truss Catastrophe", "diff": 1097, "places": [["JToH", "The Eternal Abyss"], ["CTT", "Domain 1"]]},
  {"id": 286, "abbr": "ToPA", "name": "Tower of Perplexed Ascent", "diff": 1098, "places": [["Place", ""]], "game": "https://www.roblox.com/games/14477908828/Tower-of-Perplexed-Ascent-Fixed"},
  {"id": 287, "abbr": "SoWTT", "name": "Steeple of World's Tightest Timer", "diff": 1108, "places": [["Place", ""]], "game": "https://www.roblox.com/games/17549288909/steeple-of-the-worlds-tightest-timer"},
  {"id": 288, "abbr": "ToLLL", "name": "Tower of Long Lasting Leukophobia", "diff": 1105, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7275802168/Tower-of-Long-Lasting-Leukophobia-V1"},
  {"id": 289, "abbr": "ToDS", "name": "Tower of Decaying Serenity", "diff": 1106, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11987886595/Tower-of-Decaying-Serenity"},
  {"id": 290, "abbr": "ToCG", "name": "Tower of Champion's Gaming", "diff": 1091, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10296461545/tower-of-champions-gaming-classic"},
  {"id": 291, "abbr": "ToTSC", "name": "Tower of The Seventh Chromosome", "diff": 1112, "places": [["AHoSCT", "Spot 3"]]},
  {"id": 292, "abbr": "SoPA", "name": "Steeple of Pine Apple", "diff": 1113, "places": [["Place", ""]], "game": "https://www.roblox.com/games/14015694646/Steeple-of-Pine-Apple"},
  {"id": 293, "abbr": "ToDDD", "name": "Tower of Doubly Deadly Descent", "diff": 1145, "places": [["Place", ""]], "game": "https://www.roblox.com/games/17881568264/hi"},
  {"id": 294, "abbr": "ToTP", "name": "Tower of Terse Persecution", "diff": 1174, "places": [["Place", ""]], "game": "https://www.roblox.com/games/5894331183/Tower-of-Terse-Persecution"},     
  {"id": 295, "abbr": "ToEC", "name": "Tower of Elysian Crossings", "diff": 1200, "places": [["CTT", "Domain 1"]]},     
  {"id": 296, "abbr": "ToIV", "name": "Tower of Incessant Vexation", "diff": 1203, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15946290989/Tower-of-Incessant-Vexation"},    
  {"id": 297, "abbr": "ToTIW", "name": "Tower of The Ice Wall", "diff": 1204, "places": [["Place", ""]], "game": "https://www.roblox.com/games/13821901105/Tower-of-The-Ice-Wall"},
  {"id": 298, "abbr": "DT", "name": "Doomsday Tower", "diff": 1205, "places": [["Place", ""]], "game": "https://www.roblox.com/games/4361181088/Doomsday-tower"},
  {"id": 299, "abbr": "ToTB", "name": "Tower of The Bussin", "diff": 1210, "places": [["Place", ""]], "game": "https://www.roblox.com/games/13805847493/Tower-of-The-Bussin"},
  {"id": 300, "abbr": "ToTA", "name": "Tower of Truss Anarchy", "diff": 1214, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10939670001/Tower-of-The-Truss-Behemoth"},
  {"id": 301, "abbr": "ToDP", "name": "Tower of Devious Purism", "diff": 1217, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15704325043/Tower-of-Devious-Purism"},        
  {"id": 302, "abbr": "ToHO", "name": "Tower of Hollow Obstacles", "diff": 1228, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7274150666/Tower-of-Hollow-Obstacles-Modern"},      
  {"id": 303, "abbr": "ToTBF", "name": "Tower of Timed Button Fury", "diff": 1231, "places": [["Place", ""]], "game": "https://www.roblox.com/games/130294212060932/Tower-of-Timed-Button-Fury"},    
  {"id": 304, "abbr": "NT", "name": "Nvidia Tower", "diff": 1241, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11304480507/Nvidia-Tower"},
  {"id": 305, "abbr": "ToVL", "name": "Tower of Vague Luminescence", "diff": 1248, "places": [["Place", ""]], "game": "https://www.roblox.com/games/9024799067/Tower-of-Vague-Luminescence"},    
  {"id": 306, "abbr": "ToTF", "name": "Tower of Thje Floor", "diff": 1270, "places": [["Place", ""]], "game": "https://www.roblox.com/games/12013054120/tower-of-thje-floor"},
  {"id": 307, "abbr": "ToPR", "name": "Tower of Prismal Radiance", "diff": 1268, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15010762495/Tower-of-Prismal-Radiance"},      
  {"id": 308, "abbr": "ToJC", "name": "Tower of Jaded Compromise", "diff": 1277, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11006457631/Tower-of-Jaded-Compromise"},      
  {"id": 309, "abbr": "ToDF", "name": "Tower of Disassociative Force", "diff": 1294, "places": [["Place", ""]], "game": "https://www.roblox.com/games/12368847088/Tower-of-Dissociative-Force"},
  {"id": 310, "abbr": "ToDD", "name": "Tower of Dizzyjump's Delight", "diff": 802, "places": [["TBP", "Plate 6"]]},
  {"id": 311, "abbr": "SoC", "name": "Steeple of Crohn's", "diff": 807, "places": [["TBP", "Plate 10"]]},
  {"id": 312, "abbr": "SoDC", "name": "Steeple of Difficulty Chart", "diff": 811, "places": [["TBP", "Plate 8"]]},
  {"id": 313, "abbr": "EoQE", "name": "Edifice of Quarry Excavations", "diff": 815, "places": [["TBP", "Plate 7"]]},
  {"id": 314, "abbr": "ToLIA", "name": "Tower of Libyan Interdimensional Airlines", "diff": 819, "places": [["TBP", "Plate 6"]]},
  {"id": 315, "abbr": "ToCM", "name": "Tower of Cerebrum Munching", "diff": 823, "places": [["TBP", "Plate 3"]]},
  {"id": 316, "abbr": "SoCS", "name": "Spire of Crusty Socks", "diff": 840, "places": [["AToS", "April Fools 2024"], ["TBP", "Plate 10"]]},
  {"id": 317, "abbr": "ToFTBTP", "name": "Tower of Fairly Thin But Tall Pole", "diff": 848, "places": [["TBP", "Plate 9"]]},
  {"id": 318, "abbr": "EAT", "name": "Even A Tower", "diff": 914, "places": [["TBP", "Plate 10"]]},
  {"id": 319, "abbr": "SoUG", "name": "Steeple of Untitled Griddy", "diff": 918, "places": [["TBP", "Plate 6"]]},
  {"id": 320, "abbr": "BoOM", "name": "Box of Overwhelming Motorisms", "diff": 973, "places": [["TBP", "Plate 9"]]},
  {"id": 321, "abbr": "SoHH", "name": "Steeple of Hysterical Hexad", "diff": 978, "places": [["TBP", "Plate 1"]]},
  {"id": 322, "abbr": "CoLM", "name": "Citadel of Lustrum Mechanica", "diff": 983, "places": [["TBP", "Plate 12"]]},
  {"id": 323, "abbr": "ToBLT", "name": "Tower of Bacon Lettuce Tomato", "diff": 983, "places": [["TBP", "Plate 12"]]},
  {"id": 324, "abbr": "ToTSM2", "name": "Tower of The Spiciest Memes 2077", "diff": 987, "places": [["TBP", "Plate 10"]]},
  {"id": 325, "abbr": "CoSLA", "name": "Citadel of Scream Like AAAAAA", "diff": 995, "places": [["TBP", "Plate 8"]]},
  {"id": 326, "abbr": "ToETJ", "name": "Tower of Encountering The J", "diff": 996, "places": [["TBP", "Plate 11"], ["PToD", "Crystal Caverns"]]},
  {"id": 327, "abbr": "ToJH", "name": "Tower of Jittering Hands", "diff": 1002, "places": [["TBP", "Plate 9"]]},
  {"id": 328, "abbr": "ToWB", "name": "Tower of Was Bored", "diff": 1005, "places": [["PToD", "Crystal Caverns"]]},
  {"id": 329, "abbr": "ToPT", "name": "Tower of Plated Thoughts", "diff": 1009, "places": [["TBP", "Plate 11"]]},
  {"id": 330, "abbr": "EoSD", "name": "Edifice of Spherical Demise", "diff": 1020, "places": [["TBP", "Plate 12"]]},
  {"id": 331, "abbr": "ToEN", "name": "Tower of Edgy Name", "diff": 1023, "places": [["TBP", "Plate 8"]]},
  {"id": 332, "abbr": "GCoSD", "name": "Great Citadel of SUPREME DAKOTA", "diff": 1026, "places": [["TBP", "Plate 1"]]},
  {"id": 333, "abbr": "ToM", "name": "Tower of Misconception", "diff": 1032, "places": [["TBP", "Plate 11"]]},
  {"id": 334, "abbr": "SoD", "name": "Steeple of Divine", "diff": 1054, "places": [["TBP", "Plate 8"]]},
  {"id": 335, "abbr": "ToYAWL", "name": "Tower of Yelling A Whole Lot", "diff": 1058, "places": [["TBP", "Plate 5"]]},
  {"id": 336, "abbr": "SoL", "name": "Steeple of Lifelessness", "diff": 1098, "places": [["TBP", "Plate 7"]]},
  {"id": 337, "abbr": "ToSO", "name": "Tower of Simple Obstacles", "diff": 1104, "places": [["TBP", "Plate 5"]]},
  {"id": 338, "abbr": "ToHJ", "name": "Tower of Hard Jumps", "diff": 1121, "places": [["TBP", "Plate 2"]]},
  {"id": 339, "abbr": "ToLC", "name": "Tower of Lung Chugging", "diff": 1137, "places": [["TBP", "Plate 3"]]},
  {"id": 340, "abbr": "RT", "name": "Radio Tower", "diff": 1149, "places": [["TBP", "Plate 7"]]},
  {"id": 341, "abbr": "SoFP", "name": "Steeple of Four Pillars", "diff": 1223, "places": [["TBP", "Plate 9"]]},
  {"id": 342, "abbr": "ToBITS", "name": "Tower of Blimp In The Sky", "diff": 803, "places": [["AHoSCT", "Spot 2"]]},
  {"id": 343, "abbr": "CWT", "name": "Costco Wholesale Tower", "diff": 805, "places": [["LToD", "Ring 1"]]},
  {"id": 344, "abbr": "ToTSS", "name": "Tower of The Single Spiral", "diff": 805, "places": [["AHoSCT", "Spot 1"]]},
  {"id": 345, "abbr": "ToWR", "name": "Tower of Warped Reality", "diff": 812, "places": [["AHoSCT", "Spot 2"]]},
  {"id": 346, "abbr": "ToBWB", "name": "Tower of Big Wave Beach", "diff": 813, "places": [["TBP", "Plate 11"]]},
  {"id": 347, "abbr": "ToII", "name": "Tower of Incoherent Insanity", "diff": 823, "places": [["LToD", "Ring 2"]]},
  {"id": 348, "abbr": "ToOL", "name": "Tower of Obbyist's League", "diff": 831, "places": [["AHoSCT", "Spot 1"]]},
  {"id": 349, "abbr": "SoWA", "name": "Steeple of Winds Away", "diff": 844, "places": [["AHoSCT", "Spot 1"]]},
  {"id": 350, "abbr": "ToMRA:D", "name": "Tower of Movin' Right Along: DEToH", "diff": 868, "places": [["DEToH", "District 1"]]},
  {"id": 351, "abbr": "ToAN", "name": "Tower of Absolute Nonsense", "diff": 881, "places": [["AHoSCT", "Spot 2"]]},
  {"id": 352, "abbr": "ToBM", "name": "Tower of Bitter Melancholy", "diff": 917, "places": [["AHoSCT", "Spot 2"]]},
  {"id": 353, "abbr": "ToDF", "name": "Tower of Decieving Failure", "diff": 929, "places": [["AHoSCT", "Spot 1"]]},
  {"id": 354, "abbr": "ToTS", "name": "Tower of Trouble Sleeping", "diff": 935, "places": [["AHoSCT", "Spot 1"]]},
  {"id": 355, "abbr": "ToPV", "name": "Tower of Prestigious Void", "diff": 1001, "places": [["TBP", "Plate 13"]]},
  {"id": 356, "abbr": "ToTL:U", "name": "Tower of Thinning Layers: Unnerfed", "diff": 1021, "places": [["Place", ""]], "game": "https://www.roblox.com/games/6136417948/Unnerfed-ToTL-Itemless-W-O-camera-bug"},
  {"id": 357, "abbr": "ToROT", "name": "Tower of Runnin' Outta Time", "diff": 1032, "places": [["AHoSCT", "Spot 1"]]},
  {"id": 358, "abbr": "ToVP", "name": "Tower of Varying Punishment", "diff": 1044, "places": [["AHoSCT", "Spot 1"]]},
  {"id": 359, "abbr": "ToHH", "name": "Tower of Hasty Hurdles", "diff": 984, "places": [["AHoSCT", "Spot 2"]]},
  {"id": 360, "abbr": "ToMRA", "name": "Tower of Movin' Right Along", "diff": 1092, "places": [["Place", ""]], "game": "https://www.roblox.com/games/71355551204768/Tower-of-Movin-Right-Along"},
  {"id": 361, "abbr": "ToIBTW", "name": "Tower of I Beat Tidal Wave", "diff": 1097, "places": [["Place", ""]], "game": "https://www.roblox.com/games/6202328566/Tower-of-I-Beat-Tidal-Wave"},
  {"id": 362, "abbr": "ToPaC", "name": "Tower of Peace and Chaos", "diff": 1116, "places": [["AHoSCT", "Spot 1"]]},
  {"id": 363, "abbr": "ToAR:U", "name": "Tower of Alien Radiance: Unnerfed", "diff": 1193, "places": [["Place", ""]], "game": "https://www.roblox.com/games/5484667482/Tower-of-Alien-Radiance-Unnerfed"},
  {"id": 364, "abbr": "ToHAO", "name": "Tower of Harsh Aesthetical Obstacles", "diff": 802, "places": [["PToH", "Ring 1"]]}, 
  {"id": 365, "abbr": "ToSM", "name": "Tower of Space Management", "diff": 803, "places": [["ZToA", "Dimension 2"]]},        
  {"id": 366, "abbr": "ToSP", "name": "Tower of Silent Panic", "diff": 807, "places": [["ZToA", "Regret's Cave"]]},
  {"id": 367, "abbr": "SoCB:SN", "name": "Steeple of Cheese Burger: Super Nerf", "diff": 824, "places": [["ATS", "Ring 3"]]},    
  {"id": 368, "abbr": "ToEL", "name": "Tower of Expanding Layers", "diff": 826, "places": [["ZToA", "Ring 1"]]},
  {"id": 369, "abbr": "ToCG", "name": "Tower of Cataclysmic Galore", "diff": 828, "places": [["PToH", "Ring 2"]]},
  {"id": 370, "abbr": "ToAU", "name": "Tower of Aesthetic Urbanization", "diff": 841, "places": [["PToH", "Ring 5"]]},       
  {"id": 371, "abbr": "ToEA", "name": "Tower of Enraging Advancement", "diff": 857, "places": [["PToH", "Ring 1"]]},
  {"id": 372, "abbr": "ToNW", "name": "Tower of Northern Winds", "diff": 872, "places": [["PToH", "Ring 5"]]},
  {"id": 373, "abbr": "ToJHG", "name": "Tower of Just Hard Gameplay", "diff": 861, "places": [["ZToA", "Ring 2"]]},
  {"id": 374, "abbr": "ToAH", "name": "Tower of Arctic Hollows", "diff": 891, "places": [["PToH", "Confectionary Caverns"]]},
  {"id": 375, "abbr": "ToES", "name": "Tower of Elaborate Solutions", "diff": 893, "places": [["ZToA", "Dimension 1"]]},     
  {"id": 376, "abbr": "ToC", "name": "Tower of Contraposition", "diff": 893, "places": [["PToH", "Ring 4"]]},
  {"id": 377, "abbr": "ToCS", "name": "Tower of Contemporary Simplicity", "diff": 898, "places": [["ZToA", "Ring 3"]]},      
  {"id": 378, "abbr": "ToS", "name": "Tower of Stigmatism", "diff": 903, "places": [["PToH", "Ring 2"]]},
  {"id": 379, "abbr": "RoGN", "name": "Room of Ghoulish Necromancy", "diff": 911, "places": [["PToH", "Pit of Peril"]]},     
  {"id": 380, "abbr": "ToCT", "name": "Tower of Classical Torment", "diff": 921, "places": [["ZToA", "Regret's Cave"]]},     
  {"id": 381, "abbr": "ToTF", "name": "Tower of The Fog", "diff": 928, "places": [["Place", ""]], "game": "https://www.roblox.com/games/8837686495/totf"},
  {"id": 382, "abbr": "ToOR", "name": "Tower of Occurring Ramifications", "diff": 931, "places": [["Place", ""]], "game": "https://www.roblox.com/games/8356040115/Tower-of-Occurring-Ramifications/"},
  {"id": 383, "abbr": "ToPaAJ", "name": "Tower of Precise and Accurate Jumps", "diff": 934, "places": [["PToH", "Ring 5"]]}, 
  {"id": 384, "abbr": "ToLI", "name": "Tower of Leaning Interferences", "diff": 946, "places": [["PToH", "Ring 4"]]},        
  {"id": 385, "abbr": "ToDM", "name": "Tower of Divine Mastery", "diff": 950, "places": [["Place", ""]], "game": "https://www.roblox.com/games/8492235861/Tower-of-Divine-Mastery"},
  {"id": 386, "abbr": "ToSIP", "name": "Tower of Senseless Internal Pain", "diff": 950, "places": [["ZToA", "Ring 1"]]},     
  {"id": 387, "abbr": "ToEE", "name": "Tower of Exuberant Encumbrances", "diff": 957, "places": [["Place", ""]], "game": "https://www.roblox.com/games/117311205516764/towerr-of-exuberant-encumbrances-if-it-was-good"},
  {"id": 388, "abbr": "ToGS", "name": "Tower of Goofy Stickers", "diff": 960, "places": [["Place", ""]], "game": "https://www.roblox.com/games/1487934841/Tower-of-Goofy-Stickers"},
  {"id": 389, "abbr": "ToAR", "name": "Tower of Appalling Ramification", "diff": 967, "places": [["ZToA", "Regret's Cave"]]},
  {"id": 390, "abbr": "ToMSP", "name": "Tower of Mass Severe Punishment", "diff": 969, "places": [["Place", ""]], "game": "https://www.roblox.com/games/16512699324/tower-of-mass-severe-punishment"},
  {"id": 391, "abbr": "ToB", "name": "Tower of Bernard", "diff": 970, "places": [["PToH", "Ring 4"]]},
  {"id": 392, "abbr": "ToUGC", "name": "Tower of Unknown Geometrical Calculations", "diff": 837, "places": [["MToH", "Place 2"]]},
  {"id": 393, "abbr": "ToATG", "name": "Tower of Ascent To Glory", "diff": 972, "places": [["RT", "Area 1"]]},
  {"id": 394, "abbr": "ToUV", "name": "Tower of Upended Vapor", "diff": 982, "places": [["PToH", "Ring 4"]]},
  {"id": 395, "abbr": "ToSI", "name": "Tower of Skill Immersion", "diff": 989, "places": [["AToBM", "Zone 5"]]},
  {"id": 396, "abbr": "ToPA", "name": "Tower of Palette Annihilation", "diff": 990, "places": [["ZToA", "Dimension 2"]]},
  {"id": 397, "abbr": "ToGAR", "name": "Tower of Going Against Reality", "diff": 997, "places": [["CTT", "Domain 1"]]},
  {"id": 398, "abbr": "ToMT:GBJ", "name": "Tower of Mean Tasks: GBJ Edition", "diff": 999, "places": [["JToH", "Ring 8"]]},
  {"id": 399, "abbr": "ToMT", "name": "Tower of Mark Tower", "diff": 1004, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11709267392/Tower-Of-Mark-Tower"},
  {"id": 400, "abbr": "ToBP", "name": "Tower of Blast Power", "diff": 1006, "places": [["CTT", "Domain 1"]]},
  {"id": 401, "abbr": "ToCC", "name": "Tower of Corrupting Consequences", "diff": 1010, "places": [["ZToA", "Regret's Cave"]]},
  {"id": 402, "abbr": "ToMD", "name": "Tower of Metropolis Downpour", "diff": 1011, "places": [["PToH", "Ring 5"]]},
  {"id": 403, "abbr": "ToCA", "name": "Tower of Chromatic Acrimony", "diff": 1014, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15856245390/Tower-of-Chromatic-Acrimony-AToS-Vers"},
  {"id": 404, "abbr": "SoAToT", "name": "Steeple of A Ton of Tears", "diff": 1017, "places": [["Place", ""]], "game": "https://www.roblox.com/games/8755005732/Steeple-of-a-Ton-of-Tears"},
  {"id": 405, "abbr": "ToDO", "name": "Tower of Dripping Obstacles", "diff": 1025, "places": [["PToH", "Ring 3"]]},
  {"id": 406, "abbr": "ToRT", "name": "Tower of Radiant Terror", "diff": 1035, "places": [["PToH", "Ring 5"]]},
  {"id": 407, "abbr": "ToFI", "name": "Tower of Fervent Imperfection", "diff": 1105, "places": [["Place", ""]], "game": "https://www.roblox.com/games/8615728938/Tower-of-Fervent-Imperfection"},
  {"id": 408, "abbr": "ToDL", "name": "Tower of Disengaging Lunacy", "diff": 1140, "places": [["ZToA", "Regret's Cave"]]},
  {"id": 409, "abbr": "ToJS", "name": "Tower of Jolly Situations (CE2024)", "diff": 927, "places": [["Place", ""]], "game": "https://www.roblox.com/games/17651463073/Tower-of-Jolly-Situations"},
  {"id": 410, "abbr": "MT", "name": "Mercadona Tower", "diff": 1106, "places": [["Place", ""]], "game": "https://www.roblox.com/games/14051767134/Mercadona-Tower-V2-2"},
  {"id": 411, "abbr": "ToIR", "name": "Tower of Interdimensional Rifts", "diff": 1113, "places": [["Place", ""]], "game": "https://www.roblox.com/games/12159416614/ir-Catastrophic-Edition"},
  {"id": 412, "abbr": "ToSF", "name": "Tower of Silly Furry", "diff": 1115, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15986576744/Tower-of-Submissive-Furry"},
  {"id": 413, "abbr": "SoU", "name": "Steeple of Upsetting", "diff": 1118, "places": [["Place", ""]], "game": "https://www.roblox.com/games/16946787850/Steeple-of-Upsetting"},
  {"id": 414, "abbr": "SoRT", "name": "Steeple of Repetitive Tries", "diff": 1116, "places": [["Place", ""]], "game": "https://www.roblox.com/games/5229022645/Steeple-of-Repetitive-Tries"},
  {"id": 415, "abbr": "ToLTD", "name": "Tower of Light To Dark", "diff": 1123, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10910711689/Tower-of-Light-to-Dark"},
  {"id": 416, "abbr": "SoWRB", "name": "Steeple of Was Really Bored", "diff": 1120, "places": [["Place", ""]], "game": "https://www.roblox.com/games/18455985760/tower-of-was-really-bored"},
  {"id": 417, "abbr": "ToHC", "name": "Tower of Hectic Corridor", "diff": 1122, "places": [["Place", ""]], "game": "https://www.roblox.com/games/16992752983/Tower-of-Hectic-Corridor"},
  {"id": 418, "abbr": "SoXPD", "name": "Steeple of Xei Pei Disagreement", "diff": 1136, "places": [["Place", ""]], "game": "https://www.roblox.com/games/17464421497/Tower-of-Xei-Pei-Disagreement"},
  {"id": 419, "abbr": "ToAP", "name": "Tower of Angled Passageways", "diff": 1128, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10444873023/Tower-of-Angled-Passageways"},
  {"id": 420, "abbr": "ToFM", "name": "Tower of Fiend Massacre", "diff": 1134, "places": [["Place", ""]], "game": "https://www.roblox.com/games/12391517125/Tower-of-Fiend-Massacre"},
  {"id": 421, "abbr": "ToSCD", "name": "Tower of Speedy Cat Deluxe", "diff": 1110, "places": [["Place", ""]], "game": "https://www.roblox.com/games/14461000205/Tower-of-speedy-cat-deluxe"},
  {"id": 422, "abbr": "ToAA", "name": "Tower of Arduous Architecture", "diff": 1127, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15627936688/Arduous-Architecture"},
  {"id": 423, "abbr": "SoB", "name": "Steeple of Benevolence", "diff": 1129, "places": [["Place", ""]], "game": "https://www.roblox.com/games/99333147072120/Steeple-of-Benevolence"},
  {"id": 424, "abbr": "ToWTD", "name": "Tower of Wacky Truss Destruction", "diff": 1130, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10487771050/Tower-of-Wacky-Truss-Destruction"},      
  {"id": 425, "abbr": "SoC", "name": "Steeple of Coconut", "diff": 1146, "places": [["Place", ""]], "game": "https://www.roblox.com/games/12660723673/tower"},
  {"id": 426, "abbr": "CoCD", "name": "Citadel of Colorless Despair", "diff": 1150, "places": [["Place", ""]], "game": "https://www.roblox.com/games/6271955799/Citadel-of-Colorless-Despair"},
  {"id": 427, "abbr": "ToPA", "name": "Tower of Pure Ability", "diff": 1149, "places": [["Place", ""]], "game": "https://www.roblox.com/games/5205122975/Tower-of-Pure-Ability"},
  {"id": 428, "abbr": "ToMMM", "name": "Tower of Monty Mole Mayhem", "diff": 1143, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10382407112/Tower-of-Monty-Mole-Mayhem"},
  {"id": 429, "abbr": "ToML", "name": "Tower of Memory Leak", "diff": 1144, "places": [["Place", ""]], "game": "https://www.roblox.com/games/16733665925/Tower-of-Mogging-Kai-Cenat"},
  {"id": 430, "abbr": "ToYIPEE", "name": "Tower of Yeah, It's Pretty Empty Entirely", "diff": 1145, "places": [["Place", ""]], "game": "https://www.roblox.com/games/13167713343/Tower-of-Yeah-Its-Pretty-Empty-Entirely"},
  {"id": 431, "abbr": "ToLTD", "name": "Tower of Live The Dream", "diff": 1151, "places": [["Place", ""]], "game": "https://www.roblox.com/games/14809363536/Tower-of-Live-The-Dream"},
  {"id": 432, "abbr": "ToRE", "name": "Tower of Reproachful Eyewall", "diff": 1148, "places": [["Place", ""]], "game": "https://www.roblox.com/games/17231735138/Tower-of-Reproachful-Eyewall"},
  {"id": 433, "abbr": "ToDNP", "name": "Tower of Do Not Play", "diff": 1171, "places": [["Place", ""]], "game": "https://www.roblox.com/games/18300663861/tower-dump"},
  {"id": 434, "abbr": "ToPR", "name": "Tower of Punishing Runs", "diff": 1160, "places": [["Place", ""]], "game": "https://www.roblox.com/games/17448439101/Tower-of-Punishing-Runs"},
  {"id": 435, "abbr": "ToMA", "name": "Tower of Monumental Abyss", "diff": 1156, "places": [["CTT", "Domain 1"]]},
  {"id": 436, "abbr": "SoKnP", "name": "Steeple of Kyodai na Paul", "diff": 1185, "places": [["Place", ""]], "game": "https://www.roblox.com/games/17755383688/Steeple-of-Kyodai-na-Paul"},
  {"id": 437, "abbr": "ToEMW", "name": "Tower of Explore My World", "diff": 1170, "places": [["CTT", "Domain 1"]]},
  {"id": 438, "abbr": "ToV", "name": "Tower of Vertigo", "diff": 1190, "places": [["HT", "Ring 1"]]},
  {"id": 439, "abbr": "ToT2", "name": "Tower of Tarapop 2", "diff": 1175, "places": [["Place", ""]], "game": "https://www.roblox.com/games/18648268252/tower-of-tarapop-2"},
  {"id": 440, "abbr": "ToCK", "name": "Tower of Corner Kerfuffle", "diff": 1185, "places": [["Place", ""]], "game": "https://www.roblox.com/games/13883380027/Tower-of-Corner-Kerfuffle"},
  {"id": 441, "abbr": "ToPC", "name": "Tower of Prolonged Condemnation", "diff": 1194, "places": [["Place", ""]], "game": "https://www.roblox.com/games/18647810353/Tower-of-Prolonged-Condemnation"},
  {"id": 442, "abbr": "SoPPP", "name": "Steeple of Pole Pole Pole", "diff": 1186, "places": [["Place", ""]], "game": "https://www.roblox.com/games/4890784351/Steeple-of-Pole-Pole-Pole"},
  {"id": 443, "abbr": "ToFNM", "name": "Tower of Fujiwara No Mokou", "diff": 1198, "places": [["Place", ""]], "game": "https://www.roblox.com/games/14806865886/Tower-of-Fujiwara-no-Mokou"},
  {"id": 444, "abbr": "ToM", "name": "Tower of Meaningfulness", "diff": 1196, "places": [["Place", ""]], "game": "https://www.roblox.com/games/16744721624/Tower-of-Meaningfulness"},
  {"id": 445, "abbr": "ToFA", "name": "Tower of Flimsy Architecture", "diff": 806, "places": [["TG", "Zone 2"]]},
  {"id": 446, "abbr": "ToARCS", "name": "Tower of A Rainbow Colored Septentrion", "diff": 810, "places": [["AHoSCT", "Spot 3"]]},  
  {"id": 447, "abbr": "ToNC", "name": "Tower of Nefarious Confrontations", "diff": 814, "places": [["AToBM", "Zone 6"]]},
  {"id": 448, "abbr": "ToFH", "name": "Tower of Fatal Heights", "diff": 827, "places": [["AHoSCT", "Spot 3"]]},
  {"id": 449, "abbr": "ToBI", "name": "Tower of Blissful Ignorance", "diff": 835, "places": [["AToBM", "Zone 6"]]},
  {"id": 450, "abbr": "ToOLC:N", "name": "Tower of Overthinking Life Choices: Nerf", "diff": 839, "places": [["PoM:N", "Ring 1"]]},
  {"id": 451, "abbr": "ToHE", "name": "Tower of Harsh Endeavour", "diff": 842, "places": [["TG", "Zone 1"]]},
  {"id": 452, "abbr": "ToBM", "name": "Tower of Bruh Moments", "diff": 862, "places": [["AToBM", "Zone 4"]]},
  {"id": 453, "abbr": "ToVS", "name": "Tower of Vast Scarcity", "diff": 868, "places": [["PToD", "Level 1"]]},
  {"id": 454, "abbr": "ToPaD", "name": "Tower of Pits and Death", "diff": 873, "places": [["PToD", "Level 2"]]},
  {"id": 455, "abbr": "ToCW", "name": "Tower of Climbing Wall", "diff": 882, "places": [["PToD", "Sakura Village"]]},
  {"id": 456, "abbr": "ToPE", "name": "Tower of Pure Evil", "diff": 889, "places": [["MCToH", "Mirror Domain"]]},
  {"id": 457, "abbr": "ToVI", "name": "Tower of Vibrant Infiltration", "diff": 890, "places": [["Place", ""]], "game": "https://www.roblox.com/games/13519706057/Tower-of-Vibrant-Infiltration"},
  {"id": 458, "abbr": "ToTL:DC", "name": "Tower of Thinning Layers: Difficulty Chart", "diff": 849, "places": [["Place", ""]], "game": "https://www.roblox.com/games/6666406807/Tower-of-Thinning-Layers-Difficulty-Chart"},    
  {"id": 459, "abbr": "ToSFF", "name": "Tower of Short French Fries", "diff": 901, "places": [["PToD", "Level 5"]]},
  {"id": 460, "abbr": "ToLI", "name": "Tower of Linked Insanity", "diff": 904, "places": [["AToBM", "Zone 3"]]},
  {"id": 461, "abbr": "ToVM:N", "name": "Tower of Vindictive Maneuvers: Nerf", "diff": 916, "places": [["PoM:N", "Ring 1"]]},      
  {"id": 462, "abbr": "ToAWC", "name": "Tower of A Weird Combination", "diff": 822, "places": [["PToD", "Level 3"]]},
  {"id": 463, "abbr": "ToBtC", "name": "Tower of Breaking the Core", "diff": 933, "places": [["AHoSCT", "Spot 3"]]},
  {"id": 464, "abbr": "ToAS", "name": "Tower of Agonizing Spinners", "diff": 940, "places": [["TG", "Zone 3"]]},
  {"id": 465, "abbr": "ToAIE", "name": "Tower of Ascent Into Exile", "diff": 941, "places": [["Place", ""]], "game": "https://www.roblox.com/games/122701840017589/Tower-of-Ascent-Into-Exile"},
  {"id": 466, "abbr": "ToAD", "name": "Tower of Austere Designs", "diff": 951, "places": [["Place", ""]], "game": "https://www.roblox.com/games/13747010209/austere-designs-itemless"},
  {"id": 467, "abbr": "ToPR", "name": "Tower of Prolonged Runs", "diff": 953, "places": [["Place", ""]], "game": "https://www.roblox.com/games/5899678523/topr-classic"},
  {"id": 468, "abbr": "CoG4", "name": "Citadel of Goku 4.0", "diff": 960, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10599228237/Citadel-of-Goku-4-0-20-FLOORS"},
  {"id": 469, "abbr": "ToST", "name": "Tower of Severe Trauma", "diff": 965, "places": [["AToBM", "Zone 6"]]},
  {"id": 470, "abbr": "ToEN", "name": "Tower of Eternal Nightmares", "diff": 971, "places": [["MCToH", "World 3"]]},
  {"id": 471, "abbr": "ToGP", "name": "Tower of Gateway Protocol", "diff": 905, "places": [["Place", ""]], "game": "https://www.roblox.com/games/18885747968/Tower-of-Gateway-Protocol"}, 
  {"id": 472, "abbr": "ToP", "name": "Tower of Purification", "diff": 988, "places": [["AToBM", "Zone 3"]]},
  {"id": 473, "abbr": "ToSE:N", "name": "Tower of Shunning Excursion: Nerf", "diff": 993, "places": [["PoM:N", "Ring 1"]]},
  {"id": 474, "abbr": "ToK", "name": "Tower of Kino", "diff": 1001, "places": [["AToS", "Ring 8"]]},
  {"id": 475, "abbr": "ToAP", "name": "Tower of Abrasive Playground", "diff": 1007, "places": [["Place", ""]], "game": "https://www.roblox.com/games/18755769596/Tower-of-Abrasive-Playground"},
  {"id": 476, "abbr": "ToPD", "name": "Tower of Punishing Descent", "diff": 1013, "places": [["AHoSCT", "Spot 3"]]},
  {"id": 477, "abbr": "ToCA", "name": "Tower of Claustrophobic Anomalies", "diff": 1014, "places": [["Place", ""]], "game": "https://www.roblox.com/games/5222662980/Tower-of-Claustrophobic-Anomalies"},
  {"id": 478, "abbr": "ToNMD", "name": "Tower of Not Many Days", "diff": 1017, "places": [["AHoSCT", "Spot 2"]]},
  {"id": 479, "abbr": "ToSAO", "name": "Tower of Snaky Ascended Obstacles", "diff": 1028, "places": [["Place", ""]], "game": "https://www.roblox.com/games/6752269537/Tower-of-Snaky-Ascended-Obstacles#!/about"},
  {"id": 480, "abbr": "ToSID", "name": "Tower of Slope Into Destiny", "diff": 1020, "places": [["Place", ""]], "game": "https://www.roblox.com/games/13199134254/Tower-of-Slope-Into-Destiny"},
  {"id": 481, "abbr": "SCT", "name": "Stupid Crown Tower", "diff": 1030, "places": [["AToS", "April Fools 2023"]]},
  {"id": 482, "abbr": "ToVH:N", "name": "Tower of Vacant Hindrances: Nerf", "diff": 1039, "places": [["PoM:N", "Ring 1"]]},
  {"id": 483, "abbr": "ToBM", "name": "Tower of Bodacious Maneuvering", "diff": 1042, "places": [["HT", "Ring 1"]]},
  {"id": 484, "abbr": "ToNT", "name": "Tower of No Time", "diff": 1053, "places": [["AHoSCT", "Spot 3"], ["PToD", "Level 6"]]},
  {"id": 485, "abbr": "ToRCE", "name": "Tower of Rushed Collaborative Efforts", "diff": 877, "places": [["MToH", "Place 4"]]},
  {"id": 486, "abbr": "ToWM:N", "name": "Tower of Water Melon: Nerf", "diff": 1060, "places": [["PoM:N", "Ring 1"]]},
  {"id": 487, "abbr": "ToPN", "name": "Tower of Penultimate Nostalgia", "diff": 1063, "places": [["Place", ""]], "game": "https://www.roblox.com/games/12917426906/Tower-of-Penultimate-Nostalgia"},
  {"id": 488, "abbr": "ToDU", "name": "Tower of Double Up", "diff": 1064, "places": [["AHoSCT", "Spot 3"]]},
  {"id": 489, "abbr": "ToCP:DC", "name": "Tower of Cruel Punishment: Difficulty Chart", "diff": 1069, "places": [["Place", ""]], "game": "https://www.roblox.com/games/6745466620/Tower-of-Cruel-Punishment-Difficulty-Chart"},
  {"id": 490, "abbr": "ToTRP:N", "name": "Tower of The Roof's Pique: Nerf", "diff": 1072, "places": [["PoM:N", "Ring 1"]]},
  {"id": 491, "abbr": "ToEV:N", "name": "Tower of Eternal Void: Nerf", "diff": 1088, "places": [["PoM:N", "Ring 1"]]},
  {"id": 492, "abbr": "ToBF:N", "name": "Tower of Blind Fate: Nerf", "diff": 1101, "places": [["PoM:N", "Ring 1"]]},
  {"id": 493, "abbr": "CoIV:N", "name": "Citadel of Infinite Void: Nerf", "diff": 1125, "places": [["PoM:N", "Ring 1"]]},
  {"id": 494, "abbr": "CoGF", "name": "Citadel of Generation Failure", "diff": 1154, "places": [["Place", ""]], "game": "https://www.roblox.com/games/13721728773/Citadel-of-Generation-Failure"},
  {"id": 495, "abbr": "CoDIE", "name": "Citadel of Descent Into Exile", "diff": 1197, "places": [["Place", ""]], "game": "https://www.roblox.com/games/16247488883/Citadel-of-Descent-Into-Exile"},
  {"id": 496, "abbr": "ToSF:N", "name": "Tower of Spiralling Fates: Nerf", "diff": 1209, "places": [["PoM:N", "Ring 1"]]},
  {"id": 497, "abbr": "ToGG", "name": "Tower of Gunga Ginga", "diff": 1240, "places": [["Place", ""]], "game": "https://www.roblox.com/games/4212833822/towero-f-gunga-ginga"},
  {"id": 498, "abbr": "CoVH", "name": "Citadel of Vacant Hindrances", "diff": 1246, "places": [["Place", ""]], "game": "https://www.roblox.com/games/14400537126/Citadel-of-Vacant-Hindrances"},
  {"id": 499, "abbr": "ToSQ", "name": "Tower of Substantial Quietus", "diff": 1261, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 500, "abbr": "ToLL", "name": "Tower of Lavender Lustre", "diff": 1276, "places": [["Place", ""]], "game": "https://www.roblox.com/games/117774906877197/ToLL"},
  {"id": 501, "abbr": "ToSD", "name": "Tower of Sudden Death", "diff": 1319, "places": [["CSCD", "Scope 3"]]},
  {"id": 502, "abbr": "GCoR2", "name": "Great Citadel of Ring 2", "diff": 825, "places": [["Place", ""]], "game": "https://www.roblox.com/games/12644600101/Great-Citadel-of-Ring-2"},
  {"id": 503, "abbr": "ToEL", "name": "Tower of Escaping Lava", "diff": 853, "places": [["KT", "Kratic Tower"]]},
  {"id": 504, "abbr": "ToK", "name": "Tower of Kratic", "diff": 908, "places": [["KT", "Kratic Tower"]]},
  {"id": 505, "abbr": "ToQU", "name": "Tower of Qwerty Uiop", "diff": 1348, "places": [["JToH", "The Eternal Abyss"], ["CTT", "Domain 1"]]},
  {"id": 506, "abbr": "ToDIE", "name": "Tower of Dying Inside Eternally", "diff": 829, "places": [["AHoSCT", "Spot 2"]]},
  {"id": 507, "abbr": "ToIH", "name": "Tower of Inverted Hope", "diff": 952, "places": [["MToH", "Place 1"]]},  
  {"id": 508, "abbr": "ToNN", "name": "Tower of Neon Nightmares", "diff": 963, "places": [["MToH", "Place 4"]]},
  {"id": 509, "abbr": "SoUB", "name": "Steeple of Underlining Bleakness", "diff": 848, "places": [["JXS", "Ring 1"]]},  
  {"id": 510, "abbr": "TotP", "name": "Tower of the Planets", "diff": 910, "places": [["SMToH", "Ring 5"]]},
  {"id": 511, "abbr": "ToHG", "name": "Tower of Hella Gimmicks", "diff": 936, "places": [["JToH", "April Fools 2021"]]},
  {"id": 512, "abbr": "ToTJJ", "name": "Tower of The Jump Junkyard", "diff": 942, "places": [["CTT", "Domain 1"]]},
  {"id": 513, "abbr": "SoIM", "name": "Steeple of Irrelevant Movement", "diff": 995, "places": [["CKR", "Region 2"]]},
  {"id": 514, "abbr": "ToMJ", "name": "Tower of Miserable Journeys", "diff": 1068, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7200776444/Tower-of-Miserable-Journeys-itemed"},
]
