all_towers = [
  {"id": 1, "abbr": "ToDT", "name": "Tower of Double Trouble", "diff": 800, "places": [["JToH", "Zone 2"]]},
  {"id": 2, "abbr": "ToDC", "name": "Tower of Difficulty Chart", "diff": 809, "places": [["JToH", "Ring 2"]]},
  {"id": 3, "abbr": "TT", "name": "Thanos Tower", "diff": 813, "places": [["JToH", "Ring 1"]]},
  {"id": 4, "abbr": "ToHA", "name": "Tower of High Adrenaline", "diff": 816, "places": [["JToH", "Ring 9"]]},
  {"id": 5, "abbr": "ToEH", "name": "Tower of Extreme Hell", "diff": 817, "places": [["JToH", "Ring 7"]]},
  {"id": 6, "abbr": "ToBT", "name": "Tower of Bent Trauma", "diff": 818, "places": [["JToH", "Ring 9"]]},
  {"id": 7, "abbr": "ToUH", "name": "Tower of Unsettling Heights", "diff": 822, "places": [["JToH", "Lost River"], ["CSCD", "Scope 1"]]},
  {"id": 8, "abbr": "ToTL", "name": "Tower of Thinning Layers", "diff": 830, "places": [["JToH", "Zone 1"]]},
  {"id": 9, "abbr": "ToIF", "name": "Tower of Inevitable Failure", "diff": 845, "places": [["JToH", "Zone 4"]]},
  {"id": 10, "abbr": "ToCA", "name": "Tower of Curved Ascent", "diff": 846, "places": [["JToH", "Ring 9"], ["TBP", "Plate 13"]]},
  {"id": 11, "abbr": "ToMB", "name": "Tower of Mind Breaking", "diff": 851, "places": [["JToH", "Forgotten Ridge"]]},
  {"id": 12, "abbr": "ToIB", "name": "Tower of Icy Blizzards", "diff": 867, "places": [["JToH", "Ring 5"]]},
  {"id": 13, "abbr": "ToHR", "name": "Tower of Hollow Reformations", "diff": 872, "places": [["JToH", "Zone 9"]]},
  {"id": 14, "abbr": "ToPZ", "name": "Tower of Polychromatic Zero", "diff": 878, "places": [["JToH", "Zone 5"]]},
  {"id": 15, "abbr": "ToRER", "name": "Tower of Rough Endoplasmic Reticulum", "diff": 882, "places": [["JToH", "Zone 8"]]},
  {"id": 16, "abbr": "ToC", "name": "Tower of Confusion", "diff": 884, "places": [["JToH", "Ring 3"]]},
  {"id": 17, "abbr": "ToFaCT", "name": "Tower of Frightening and Confusing Trials", "diff": 898, "places": [["JToH", "Ring 9"]]},
  {"id": 18, "abbr": "ToAE", "name": "Tower of Astral Eclipse", "diff": 900, "places": [["JToH", "Zone 8"]]},
  {"id": 19, "abbr": "ToPB", "name": "Tower of Pannelling Barricades", "diff": 905, "places": [["JToH", "Zone 9"]]},
  {"id": 20, "abbr": "ToBK", "name": "Tower of Bloodthirsty Kenos", "diff": 912, "places": [["JToH", "Ring 9"]]},
  {"id": 21, "abbr": "ToWF", "name": "Tower of Wicked Fortress", "diff": 927, "places": [["JToH", "Ashen Towerworks"]]},
  {"id": 22, "abbr": "ToSM", "name": "Tower of Strategic Mechanics", "diff": 938, "places": [["JToH", "Ring 6"]]},
  {"id": 23, "abbr": "ToHH", "name": "Tower of Hopeless Hell", "diff": 945, "places": [["JToH", "Zone 3"]]},
  {"id": 24, "abbr": "ToTB", "name": "Tower of Terrifying Beauty", "diff": 949, "places": [["JToH", "Ring 7"]]},
  {"id": 25, "abbr": "ToSO", "name": "Tower of Suffering Outside", "diff": 954, "places": [["JToH", "Ring 8"]]},
  {"id": 26, "abbr": "ToAAA", "name": "Tower of Astronomically Aimless Annoyances", "diff": 958, "places": [["JToH", "Zone 4"]]},
  {"id": 27, "abbr": "ToTDA", "name": "Tower of The Dripping Amalgam", "diff": 961, "places": [["JToH", "Zone 6"]]},
  {"id": 28, "abbr": "ToEI", "name": "Tower of Externalizing Insanity", "diff": 994, "places": [["JToH", "Ring 8"]]},
  {"id": 29, "abbr": "ToFM", "name": "Tower of Fractured Memories", "diff": 999, "places": [["JToH", "Zone 7"]]},
  {"id": 30, "abbr": "ToIM", "name": "Tower of Impossible Movement", "diff": 1000, "places": [["JToH", "Ring 6"]]},
  {"id": 31, "abbr": "ToFN", "name": "Tower of Frightening Nightmares", "diff": 1008, "places": [["JToH", "Ring 5"]]},
  {"id": 32, "abbr": "ToMM", "name": "Tower of Micro Management", "diff": 1036, "places": [["JToH", "Zone 6"]]},
  {"id": 33, "abbr": "ToAR", "name": "Tower of Alien Radiance", "diff": 1040, "places": [["JToH", "Zone 5"]]},
  {"id": 34, "abbr": "ToNS", "name": "Tower of Nervous Sweating", "diff": 1052, "places": [["JToH", "Ring 9"]]},
  {"id": 35, "abbr": "ToUA", "name": "Tower of Uncanny Agony", "diff": 1067, "places": [["JToH", "Zone 7"]]},
  {"id": 36, "abbr": "ToWWW", "name": "Tower of Wildly Wacky Wonders", "diff": 1081, "places": [["JToH", "Zone 9"]]},
  {"id": 37, "abbr": "ToI", "name": "Tower of Inception", "diff": 1091, "places": [["JToH", "Ring 4"]]},
  {"id": 38, "abbr": "ToAM", "name": "Tower of Augmented Misery", "diff": 1100, "places": [["JToH", "Ring 9"]]},
  {"id": 39, "abbr": "ToGF", "name": "Tower of Generation Failure", "diff": 1118, "places": [["JToH", "Ring 8"]]},
  {"id": 40, "abbr": "ToEMP", "name": "Tower of Empty Meaningless Patterns", "diff": 1133, "places": [["JToH", "Zone 9"]]},
  {"id": 41, "abbr": "ToDIE", "name": "Tower of Descent Into Exile", "diff": 1142, "places": [["JToH", "Zone 8"], ["AToS", "Ring 8"]]},
  {"id": 42, "abbr": "ToCR", "name": "Tower of Champion's Road", "diff": 1171, "places": [["JToH", "Ring 9"]]},
  {"id": 43, "abbr": "ToER", "name": "Tower of Elongated Runs", "diff": 1187, "places": [["JToH", "Ring 7"]]},
  {"id": 44, "abbr": "ToCP", "name": "Tower of Cruel Punishment", "diff": 1199, "places": [["JToH", "Ring 9"]]},
  {"id": 45, "abbr": "ToXIC", "name": "Tower of Xerically Infuriating Calamity", "diff": 1002, "places": [["JToH", "Pit of Misery"]]},
  {"id": 46, "abbr": "ToOLC", "name": "Tower of Overthinking Life Choices", "diff": 1079, "places": [["JToH", "Pit of Misery"]]},
  {"id": 47, "abbr": "ToVM", "name": "Tower of Vindictive Maneuvers", "diff": 1096, "places": [["JToH", "Pit of Misery"]]},
  {"id": 48, "abbr": "ToSE", "name": "Tower of Shunning Excursion", "diff": 1166, "places": [["JToH", "Pit of Misery"]]},
  {"id": 49, "abbr": "ToVH", "name": "Tower of Vacant Hinderances", "diff": 1198, "places": [["JToH", "Pit of Misery"], ["CSCD", "Scope 1"]]},
  {"id": 50, "abbr": "ToWM", "name": "Tower of Water Melon", "diff": 1230, "places": [["JToH", "Pit of Misery"]]},
  {"id": 51, "abbr": "ToEV", "name": "Tower of Eternal Void", "diff": 1255, "places": [["JToH", "Pit of Misery"]]},
  {"id": 52, "abbr": "ToTRP", "name": "Tower of The Roof's Pique", "diff": 1260, "places": [["JToH", "Pit of Misery"], ["CSCD", "Scope 1"]]},
  {"id": 53, "abbr": "ToBF", "name": "Tower of Blind Fate", "diff": 1300, "places": [["JToH", "Pit of Misery"]]},
  {"id": 54, "abbr": "CoIV", "name": "Citadel of Infinite Void", "diff": 1323, "places": [["JToH", "Pit of Misery"]]},
  {"id": 55, "abbr": "ToSF", "name": "Tower of Spiralling Fates", "diff": 1354, "places": [["JToH", "Pit of Misery"]]},
  {"id": 56, "abbr": "ToDC:C", "name": "Tower of Difficulty Chart: Classic", "diff": 801, "places": [["Place", ""]], "game": "https://www.roblox.com/games/6183527403/ToDC-C-Tower-of-Difficulty-Chart-Classic"},
  {"id": 57, "abbr": "ToQA", "name": "Tower of Quaint Activations", "diff": 849, "places": [["JToH", "Time-Lost Sands"]]},
  {"id": 58, "abbr": "ToBD", "name": "Tower of Boreal Disarray", "diff": 852, "places": [["Place", ""]], "game": "https://www.roblox.com/games/8620395748/Tower-of-Boreal-Disarray"},
  {"id": 59, "abbr": "ToSTR", "name": "Tower of Slipping Through Reality", "diff": 863, "places": [["JToH", "Time-Lost Clockwork"]]},
  {"id": 60, "abbr": "BT", "name": "Baldi Tower", "diff": 870, "places": [["JToH", "April Fools 2021"]]},
  {"id": 61, "abbr": "ToUB", "name": "Tower of Unending Bamboozles", "diff": 873, "places": [["Place", ""]], "game": "https://www.roblox.com/games/16388763948/Tower-of-Unending-Bamboozles"},
  {"id": 62, "abbr": "SoGLUBIC", "name": "Steeple of Gears Locked Up Because It's Cold", "diff": 876, "places": [["JToH", "April Fools 2023"]]},
  {"id": 63, "abbr": "T1", "name": "Tower 1", "diff": 913, "places": [["JToH", "April Fools 2024"]]},
  {"id": 64, "abbr": "ToDB", "name": "Tower of Da Baby", "diff": 1085, "places": [["JToH", "April Fools 2021"]]},
  {"id": 65, "abbr": "ToRM", "name": "Tower of Reddish Monolith", "diff": 800, "places": [["CSCD", "Scope 1"]]},
  {"id": 66, "abbr": "ToMO", "name": "Tower of Minimal Obstacles", "diff": 859, "places": [["CSCD", "Scope 2"]]},
  {"id": 67, "abbr": "ToII", "name": "Tower of Increasing Intensity", "diff": 866, "places": [["CSCD", "Scope 2"]]},
  {"id": 68, "abbr": "ToTTO", "name": "Tower of Two To One", "diff": 878, "places": [["CSCD", "Scope 1"]]},
  {"id": 69, "abbr": "ToHR", "name": "Tower of Hellish Rouge", "diff": 880, "places": [["CSCD", "Scope 3"]]},
  {"id": 70, "abbr": "ToDB", "name": "Tower of Difficulty Breezing", "diff": 815, "places": [["CSCD", "Scope 2"]]},
  {"id": 71, "abbr": "ToBI", "name": "Tower of Baleful Impedes", "diff": 896, "places": [["CSCD", "Scope 3"]]},
  {"id": 72, "abbr": "ToCG", "name": "Tower of Clean Glass", "diff": 911, "places": [["CSCD", "Scope 1"]]},
  {"id": 73, "abbr": "ToAW", "name": "Tower of Abysmal Wrath", "diff": 919, "places": [["CSCD", "Scope 3"]]},
  {"id": 74, "abbr": "ToCaL", "name": "Tower of Circuits and Lasers", "diff": 956, "places": [["CSCD", "Scope 1"]]},
  {"id": 75, "abbr": "ToUG", "name": "Tower of Underlying Grief", "diff": 959, "places": [["CSCD", "Scope 1"]]},
  {"id": 76, "abbr": "ToRC", "name": "Tower of Raspy Cascades", "diff": 952, "places": [["CSCD", "Scope 3"]]},
  {"id": 77, "abbr": "ToUA", "name": "Tower of Uttermost Antagonism", "diff": 974, "places": [["CSCD", "Scope 2"], ["AToS", "Realm 2"]]},
  {"id": 78, "abbr": "ToTFW", "name": "Tower of THE FOREBODING WALL", "diff": 977, "places": [["CSCD", "Scope 3"]]},
  {"id": 79, "abbr": "ToSR", "name": "Tower of Shattered Resolve", "diff": 989, "places": [["CSCD", "Scope 2"]]},
  {"id": 80, "abbr": "ToLE", "name": "Tower of Lunar Expansion", "diff": 993, "places": [["CSCD", "Scope 2"]]},
  {"id": 81, "abbr": "ToPB:C", "name": "Tower of Pannelling Barricades: Classic", "diff": 997, "places": [["CSCD", "Scope 3"]]},
  {"id": 82, "abbr": "ToIP", "name": "Tower of Intricate Precision", "diff": 1006, "places": [["CSCD", "Scope 1"]]},
  {"id": 83, "abbr": "ToCM", "name": "Tower of Cliffside Madness", "diff": 1022, "places": [["CSCD", "Scope 1"], ["AToS", "Ring 8"]]},
  {"id": 84, "abbr": "ToID", "name": "Tower of Insensible Distress", "diff": 1030, "places": [["CSCD", "Scope 3"], ["TCT", "Ring 4"]]},
  {"id": 85, "abbr": "ToTSM", "name": "Tower of Two Sided Misery", "diff": 1037, "places": [["CSCD", "Scope 2"]]},
  {"id": 86, "abbr": "ToAD", "name": "Tower of Agonizing Demise", "diff": 1049, "places": [["CSCD", "Scope 2"]]},
  {"id": 87, "abbr": "ToLT", "name": "Tower of Lavish Thrones", "diff": 1056, "places": [["CSCD", "Scope 2"]]},
  {"id": 88, "abbr": "ToWV", "name": "Tower of Wayward Venture", "diff": 1071, "places": [["CSCD", "Scope 3"]]},
  {"id": 89, "abbr": "ToMA", "name": "Tower of Mauve Attestations", "diff": 1085, "places": [["CSCD", "Scope 3"]]},
  {"id": 90, "abbr": "ToIG", "name": "Tower of Inferno Galore", "diff": 1103, "places": [["CSCD", "Scope 1"]]},
  {"id": 91, "abbr": "ToG", "name": "Tower of Gelidity", "diff": 1109, "places": [["CSCD", "Scope 2"]]},
  {"id": 92, "abbr": "ToRRA", "name": "Tower of Ruthless Royal Architecture", "diff": 1114, "places": [["CSCD", "Scope 1"]]},
  {"id": 93, "abbr": "ToTM", "name": "Tower of Thin Mints", "diff": 1140, "places": [["JToH", "The Eternal Abyss"], ["CSCD", "Scope 3"]]},
  {"id": 94, "abbr": "ToU", "name": "Tower of Unorthodoxy", "diff": 1142, "places": [["CSCD", "Scope 3"]]},
  {"id": 95, "abbr": "ToNI", "name": "Tower of Necrotic Incantation", "diff": 1150, "places": [["CSCD", "Scope 2"]]},
  {"id": 96, "abbr": "STONE", "name": "S.T.O.N.E Facility", "diff": 1159, "places": [["CSCD", "Scope 2"]]},
  {"id": 97, "abbr": "ToPA", "name": "Tower of Pulsating Ambitions", "diff": 1165, "places": [["CSCD", "Scope 1"]]},
  {"id": 98, "abbr": "ToJ", "name": "Tower of Jocundigluey", "diff": 1173, "places": [["CSCD", "Scope 3"]]},
  {"id": 99, "abbr": "ToJJ", "name": "Tower of Jabberwock Jagger", "diff": 1200, "places": [["CSCD", "Scope 3"]]},
  {"id": 100, "abbr": "ToTW", "name": "Tower of Thje Wall", "diff": 1213, "places": [["JToH", "The Eternal Abyss"], ["CSCD", "Scope 3"]]},
  {"id": 101, "abbr": "ToFP", "name": "Tower of Futile Perusal", "diff": 1238, "places": [["CSCD", "Scope 2"], ["TBP", "Plate 11"]]},
  {"id": 102, "abbr": "ToLP", "name": "Tower of Lucas Penteado", "diff": 1263, "places": [["CSCD", "Scope 1"]]},
  {"id": 103, "abbr": "CoTEC", "name": "Citadel of The Eternal Calamity", "diff": 1312, "places": [["JToH", "The Eternal Abyss"], ["CSCD", "Scope 1"]]},
  {"id": 104, "abbr": "SoJoL", "name": "Steeple of Jack o' Lament", "diff": 831, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11004999814"},
  {"id": 105, "abbr": "SoPS", "name": "Steeple of Present Stairs", "diff": 847, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11702697136"},
  {"id": 106, "abbr": "SoUR", "name": "Steeple of Unwrapping Rituals", "diff": 850, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11497936961"},
  {"id": 107, "abbr": "SoWW", "name": "Steeple of Wandering Willow", "diff": 869, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11150002574"},
  {"id": 108, "abbr": "SoFF", "name": "Steeple of Fervent Festivities", "diff": 883, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11446289016/"},
  {"id": 109, "abbr": "ToFA", "name": "Tower of Festive Affairs", "diff": 928, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11506957882"},
  {"id": 110, "abbr": "ToC4", "name": "Tower of Cata4", "diff": 1126, "places": [["Place", ""]], "game": "https://www.roblox.com/games/9053906493"},
  {"id": 111, "abbr": "SoTG", "name": "Steeple of Treacherous Gnomery", "diff": 801, "places": [["AToS", "Ring 3"]]},
  {"id": 112, "abbr": "ToTU", "name": "Tower of Throttling Up", "diff": 811, "places": [["AToS", "Ring 2"]]},
  {"id": 113, "abbr": "ToMM", "name": "Tower of Medial Mayhem", "diff": 821, "places": [["AToS", "Realm 1"]]},
  {"id": 114, "abbr": "ToZ", "name": "Tower of Zigzagging", "diff": 829, "places": [["AToS", "Ring 1"]]},
  {"id": 115, "abbr": "ToLN", "name": "Tower of Loud Nine", "diff": 833, "places": [["AToS", "Realm 3"]]},
  {"id": 116, "abbr": "ToUC", "name": "Tower of Umbratic Complexity", "diff": 843, "places": [["AToS", "Ring 8"]]},
  {"id": 117, "abbr": "ToVP", "name": "Tower of Vague Perceptions", "diff": 856, "places": [["AToS", "Ring 6"]]},
  {"id": 118, "abbr": "ToCT", "name": "Tower of Contrasting Themes", "diff": 860, "places": [["AToS", "Ring 5"]]},
  {"id": 119, "abbr": "ToCP:C", "name": "Tower of Cruel Punishments", "diff": 874, "places": [["AToS", "Ring 3"]]},
  {"id": 120, "abbr": "ToC", "name": "Tower of Cognition", "diff": 888, "places": [["AToS", "Ring 4"]]},
  {"id": 121, "abbr": "ToFR", "name": "Tower of Futile Retribution", "diff": 891, "places": [["AToS", "Ring 8"]]},
  {"id": 122, "abbr": "ToNT", "name": "Tower of Nice Tasks", "diff": 894, "places": [["AToS", "Realm 4"]]},
  {"id": 123, "abbr": "ToTHT", "name": "Tower of Tee Hee Time", "diff": 899, "places": [["AToS", "Realm 4"]]},
  {"id": 124, "abbr": "ToPT", "name": "Tower of Perplexity Tabulation", "diff": 900, "places": [["AToS", "Ring 8"]]},
  {"id": 125, "abbr": "ToKT", "name": "Tower of Kyoi Tekina", "diff": 915, "places": [["AToS", "Ring 8"]]},
  {"id": 126, "abbr": "SoAD", "name": "Steeple of A Down", "diff": 920, "places": [["AToS", "Ring 4"]]},
  {"id": 127, "abbr": "ToDPA", "name": "Tower of Dangerous Pillar Adventuring", "diff": 937, "places": [["AToS", "Ring 7"]]},
  {"id": 128, "abbr": "ToPD", "name": "Tower of Pure Dopamine", "diff": 948, "places": [["AToS", "Realm 3"]]},
  {"id": 129, "abbr": "ToDED", "name": "Tower of Deep End Displeasure", "diff": 955, "places": [["AToS", "Ring 8"]]},
  {"id": 130, "abbr": "ToEA:C", "name": "Tower of Excruciating Anguish: Classic", "diff": 959, "places": [["AToS", "Ring 5"]]},
  {"id": 131, "abbr": "ToPH", "name": "Tower of Parallel Heights", "diff": 972, "places": [["AToS", "Ring 3"]]},
  {"id": 132, "abbr": "ToLA", "name": "Tower of Lus Abutendi", "diff": 976, "places": [["AToS", "Realm 4"]]},
  {"id": 133, "abbr": "ToIS", "name": "Tower of Infuriating Supplement", "diff": 991, "places": [["AToS", "Ring 8"]]},
  {"id": 134, "abbr": "ToSD", "name": "Tower of Sempiternal Disquietude", "diff": 1016, "places": [["AToS", "Ring 8"]]},
  {"id": 135, "abbr": "ToEB", "name": "Tower of Extravagant Borders", "diff": 1062, "places": [["AToS", "Ring 6"]]},
  {"id": 136, "abbr": "ToS", "name": "Tower of Seclusion", "diff": 1079, "places": [["AToS", "Ring 8"]]},
  {"id": 137, "abbr": "ToCR", "name": "Tower of Chacina Repentina", "diff": 1080, "places": [["AToS", "Ring 7"]]},
  {"id": 138, "abbr": "ToCL", "name": "Tower of Cataclysmic Layers", "diff": 1089, "places": [["AToS", "Ring 7"]]},
  {"id": 139, "abbr": "ToCI", "name": "Tower of Chromatic Inclination", "diff": 1099, "places": [["AToS", "Realm 4"]]},
  {"id": 140, "abbr": "ToRC", "name": "Tower of Rove Culmination", "diff": 1133, "places": [["AToS", "Ring 8"]]},
  {"id": 141, "abbr": "ToVS", "name": "Tower of Virulent Sojourn", "diff": 1196, "places": [["AToS", "Ring 8"]]},
  {"id": 142, "abbr": "ToABT", "name": "Tower of A Bad Time", "diff": 834, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 143, "abbr": "ToEF", "name": "Tower of Eternal Freezing", "diff": 838, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 144, "abbr": "ToCT", "name": "Tower of Chair Throwing", "diff": 855, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 145, "abbr": "CoVD", "name": "Citadel of Varying Difficulties", "diff": 871, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 146, "abbr": "ToSaP", "name": "Tower of Skill and Patience", "diff": 923, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 147, "abbr": "ToCaIG", "name": "Tower of Complex and Idiotic Gameplay", "diff": 986, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 148, "abbr": "ToSC", "name": "Tower of Swift Chacine", "diff": 1048, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 149, "abbr": "ToEO", "name": "Tower of Exodus Obscurity", "diff": 1182, "places": [["AToS", "Sword Fight Canyon"]]},
  {"id": 150, "abbr": "ToFB", "name": "Tower of Five Below", "diff": 852, "places": [["AToS", "April Fools 2023"]]},
  {"id": 151, "abbr": "ToPL", "name": "Tower of Pestiferous Line", "diff": 907, "places": [["Place", ""]], "game": "https://www.roblox.com/games/9702949317/Tower-of-Pestiferous-Twine"},
  {"id": 152, "abbr": "ToWS", "name": "Tower of Wet Socks", "diff": 949, "places": [["AToS", "April Fools 2023"]]},
  {"id": 153, "abbr": "todnd", "name": "tower of doltish ninny dunce", "diff": 955, "places": [["AToS", "April Fools 2022"]]},
  {"id": 154, "abbr": "ToUM", "name": "Tower of Umrah Market", "diff": 1047, "places": [["AToS", "April Fools 2023"]]},
  {"id": 155, "abbr": "OoTS", "name": "Obelisk of True Skill", "diff": 814, "places": [["JXXL", "Ring 1"]]},
  {"id": 156, "abbr": "OoWS", "name": "Obelisk of Wacky Strategy", "diff": 884, "places": [["JXL", "Ring 2"]]},
  {"id": 157, "abbr": "CoIT", "name": "Citadel of Indeterminate Turf", "diff": 857, "places": [["JXL", "Ring 4"]]},
  {"id": 158, "abbr": "CoTL", "name": "Citadel of Thinning Layers", "diff": 865, "places": [["JXL", "Zone 1"]]},
  {"id": 159, "abbr": "GCoLS", "name": "Great Citadel of Laptop Splitting", "diff": 879, "places": [["JXXL", "Ring 1"]]},
  {"id": 160, "abbr": "OoP", "name": "Obelisk of Peril", "diff": 886, "places": [["JXL", "Zone 1"]]},
  {"id": 161, "abbr": "TC", "name": "Thanos Citadel", "diff": 892, "places": [["JXL", "Ring 1"]]},
  {"id": 162, "abbr": "CoMB", "name": "Citadel of Mind Breaking", "diff": 896, "places": [["JXL", "Forgotten Ridge"]]},
  {"id": 163, "abbr": "CoDC", "name": "Citadel of Difficulty Chart", "diff": 943, "places": [["JXL", "Ring 2"]]},
  {"id": 164, "abbr": "CoUC", "name": "Citadel of Utter Confusion", "diff": 985, "places": [["JXL", "Ring 3"]]},
  {"id": 165, "abbr": "SCONE", "name": "S.C.O.N.E Facility", "diff": 1095, "places": [["JXL", "Ring 4"]]},
  {"id": 166, "abbr": "CoI", "name": "Citadel of Inception", "diff": 1111, "places": [["JXL", "Ring 4"]]},
  {"id": 167, "abbr": "ToRD", "name": "Tower of Ruptured Division", "diff": 895, "places": [["Place", ""]], "game": "https://www.roblox.com/games/9651122175/Tower-of-Ruptured-Division"},
  {"id": 168, "abbr": "SoJY", "name": "Steeple of Joon Yorigami", "diff": 944, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15131275415/Steeple-of-Joon-Yorigami"},
  {"id": 169, "abbr": "ToCA", "name": "Tower of Converged Agitation", "diff": 971, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10599450002/Tower-of-Converged-Agitation"},
  {"id": 170, "abbr": "ToCF", "name": "Tower of Creature Feature", "diff": 990, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15507815305/Tower-of-Creature-Feature"},
  {"id": 171, "abbr": "ToPT", "name": "Tower of Pure Torment", "diff": 932, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 172, "abbr": "ToEtA", "name": "Tower of Ease to Abyss", "diff": 968, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 173, "abbr": "ToEA", "name": "Tower of Excruciating Anguish", "diff": 1029, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 174, "abbr": "ToHN", "name": "Tower of Hellish Nightmares", "diff": 1062, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 175, "abbr": "ToUP", "name": "Tower of Unrelenting Precipice", "diff": 1087, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 176, "abbr": "ToQ", "name": "Tower of Quadrilaterals", "diff": 1096, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 177, "abbr": "ToOE", "name": "Tower of Otherworldly Expertise", "diff": 1108, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 178, "abbr": "ToTO", "name": "Tower of Tortuous Oblivion", "diff": 1139, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 179, "abbr": "ToC", "name": "Tower of Centchade", "diff": 1148, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 180, "abbr": "ToHG", "name": "Tower of Heaven's Gate", "diff": 1177, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 181, "abbr": "ToMN", "name": "Tower of Malefic Nuisances", "diff": 1219, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 182, "abbr": "SoD", "name": "Steeple of Daze", "diff": 1227, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 183, "abbr": "ToTSTL", "name": "Tower of The Sky's The Limit", "diff": 1236, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 184, "abbr": "ToFA", "name": "Tower of Flagrant Aggravation", "diff": 1244, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 185, "abbr": "ToQD", "name": "Tower of Quite Devious", "diff": 1251, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 186, "abbr": "ToIR", "name": "Tower of Irritating Results", "diff": 809, "places": [["TCT", "Timeless Archipelago"]]},
  {"id": 187, "abbr": "ToFoH", "name": "Tower of Fear of Heights", "diff": 821, "places": [["TCT", "Ring 4"]]},
  {"id": 188, "abbr": "CoR", "name": "Citadel of Rampancy", "diff": 824, "places": [["TCT", "Ring 4"]]},
  {"id": 189, "abbr": "ToTC", "name": "Tower of Tilt Controls", "diff": 836, "places": [["TCT", "Ring 2"]]},
  {"id": 190, "abbr": "SoSES", "name": "Steeple of Side Eye Scaling", "diff": 850, "places": [["TCT", "Sunset Farlands"]]},
  {"id": 191, "abbr": "ToHR:C", "name": "Tower of Hellish Rouge: Classic", "diff": 876, "places": [["TCT", "Ring 1"]]},
  {"id": 192, "abbr": "ToSD", "name": "Tower of Sitting Down", "diff": 897, "places": [["TCT", "Ring 3"]]},
  {"id": 193, "abbr": "ToGG", "name": "Tower of Googoo Gaagaa", "diff": 948, "places": [["TCT", "Ring 3"]]},
  {"id": 194, "abbr": "ToNA", "name": "Tower of Neverending Agony", "diff": 985, "places": [["TCT", "Ring 4"]]},
  {"id": 195, "abbr": "ToNR", "name": "Tower of Negative Reinforcement", "diff": 992, "places": [["TCT", "Timeless Archipelago"]]},
  {"id": 196, "abbr": "CoLD", "name": "Citadel of Love Death", "diff": 817, "places": [["NCoH", "Ring 2"]]},
  {"id": 197, "abbr": "CoUC", "name": "Citadel of Upended Chromatism", "diff": 832, "places": [["NCoH", "Ring 1"]]},
  {"id": 198, "abbr": "CoHSR", "name": "Citadel of High Sky Rise", "diff": 886, "places": [["NCoH", "Ring 1"]]},
  {"id": 199, "abbr": "ToTDS", "name": "Tower of The DiCaprio Story", "diff": 906, "places": [["Place", ""]], "game": "https://www.roblox.com/games/13222620808/Tower-of-The-DiCaprio-Story"},
  {"id": 200, "abbr": "ToHE", "name": "Tower of Hotel Exploration", "diff": 1034, "places": [["Place", ""]], "game": "https://www.roblox.com/games/8714551508/Tower-of-Hotel-Exploration"},
  {"id": 201, "abbr": "CoS", "name": "Citadel of Subway", "diff": 825, "places": [["NCoH", "Ring 3"]]},
  {"id": 202, "abbr": "CoCCC", "name": "Citadel of Condescendingly Convulsive Climbing", "diff": 946, "places": [["NCoH", "Ring 3"]]},
  {"id": 203, "abbr": "ToP", "name": "Tower of Persistence", "diff": 804, "places": [["TWR$", "Ring 3"]]},
  {"id": 204, "abbr": "ToBP", "name": "Tower of Big Pain", "diff": 827, "places": [["TWR$", "Ring 2"]]},
  {"id": 205, "abbr": "ToCT", "name": "Tower of Carpal Tunnels", "diff": 885, "places": [["TWR$", "Ring 1"]]},
  {"id": 206, "abbr": "ToBS", "name": "Tower of Both Sides", "diff": 902, "places": [["TWR$", "Ring 2"]]},
  {"id": 207, "abbr": "TT", "name": "Thor Tower", "diff": 924, "places": [["TWR$", "Ring 3"]]},
  {"id": 208, "abbr": "ToS", "name": "Tower of Silver", "diff": 979, "places": [["TWR$", "Ring 2.5"]]},
  {"id": 209, "abbr": "SoIC", "name": "Steeple of Imminent Control", "diff": 806, "places": [["KToN", "Section 2"]]},
  {"id": 210, "abbr": "SoFP", "name": "Steeple of Fabled Passage", "diff": 810, "places": [["KToN", "Section 1"]]},
  {"id": 211, "abbr": "SoKR", "name": "Steeple of Kutsen Rouge", "diff": 846, "places": [["KToN", "Section 3"]]},
  {"id": 212, "abbr": "SoPE", "name": "Steeple of Plaque Etiquette", "diff": 909, "places": [["KToN", "Section 2"]]},
  {"id": 213, "abbr": "SoPG", "name": "Steeple of Prolific Gardens", "diff": 975, "places": [["KToN", "Section 3"]]},
  {"id": 214, "abbr": "ToTW:SN", "name": "Tower of Thje Wall: Super Nerf", "diff": 808, "places": [["ATS", "Ring 3"]]},
  {"id": 215, "abbr": "ToTWV:SN", "name": "Tower of The Wedges Vengeance: Super Nerf", "diff": 815, "places": [["ATS", "Ring 2"]]},
  {"id": 216, "abbr": "ToOE:SN", "name": "Tower of Otherworldly Expertise: Super Nerf", "diff": 820, "places": [["ATS", "Ring 3"]]},
  {"id": 217, "abbr": "ToVS:SN", "name": "Tower of Virulent Sojourn: Super Nerf", "diff": 832, "places": [["ATS", "Ring 2"]]},
  {"id": 218, "abbr": "ToEV:SN", "name": "Tower of Eternal Void: Super Nerf", "diff": 834, "places": [["ATS", "Ring 1"]]},
  {"id": 219, "abbr": "ToWM:SN", "name": "Tower of Water Melon: Super Nerf", "diff": 837, "places": [["ATS", "Ring 1"]]},
  {"id": 220, "abbr": "ToFP:SN", "name": "Tower of Futile Perusal: Super Nerf", "diff": 854, "places": [["ATS", "Ring 1"]]},
  {"id": 221, "abbr": "STONE:SN", "name": "S.T.O.N.E Facility: Super Nerf", "diff": 864, "places": [["ATS", "Ring 2"]]},
  {"id": 222, "abbr": "ToCL:SN", "name": "Tower of Cataclysmic Layers: Super Nerf", "diff": 865, "places": [["ATS", "Ring 1"]]},
  {"id": 223, "abbr": "ToSM", "name": "Tower of Scintillating Microscale", "diff": 866, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10059770223/Tower-of-Scintillating-Microscale"},
  {"id": 224, "abbr": "ToUC:SN", "name": "Tower of Un Ca: Super Nerf", "diff": 875, "places": [["ATS", "Ring 3"]]},
  {"id": 225, "abbr": "ToMN:SN", "name": "Tower of Malefic Nuisances: Super Nerf", "diff": 887, "places": [["ATS", "Ring 3"]]},
  {"id": 226, "abbr": "IT:SN", "name": "Ikea Tower: Super Nerf", "diff": 889, "places": [["ATS", "Ring 1"]]},
  {"id": 227, "abbr": "ToSR:SN", "name": "Tower of Spiritual Rise: Super Nerf", "diff": 890, "places": [["ATS", "Ring 1"]]},
  {"id": 228, "abbr": "ToCP:SN", "name": "Tower of Cruel Punishment: Super Nerf", "diff": 894, "places": [["ATS", "Ring 3"]]},
  {"id": 229, "abbr": "ToP:SN", "name": "Tower of Paradise: Super Nerf", "diff": 926, "places": [["ATS", "Ring 2"]]},
  {"id": 230, "abbr": "ToBF:SN", "name": "Tower of Blind Fate: Super Nerf", "diff": 930, "places": [["ATS", "Ring 1"]]},
  {"id": 231, "abbr": "ToSA:SN", "name": "Tower of Spatial Awareness: Super Nerf", "diff": 947, "places": [["ATS", "Ring 3"]]},
  {"id": 232, "abbr": "ToQU:SN", "name": "Tower of Qwerty Uiop: Super Nerf", "diff": 974, "places": [["ATS", "Ring 2"]]},
  {"id": 233, "abbr": "CoTEC:SN", "name": "Citadel of The Eternal Calamity: Super Nerf", "diff": 1003, "places": [["ATS", "Ring 1"]]},
  {"id": 234, "abbr": "ToSF:SN", "name": "Tower of Spiralling Fates: Super Nerf", "diff": 1043, "places": [["ATS", "Ring 1"]]},
  {"id": 235, "abbr": "ToSaFT", "name": "Tower of Short and Fatal Trouble", "diff": 1046, "places": [["Place", ""]], "game": "https://www.roblox.com/games/13781276177/Tower-of-Short-and-Fatal-Trouble-TTT"},
  {"id": 236, "abbr": "ToTC", "name": "Tower of Thje Corner", "diff": 1059, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11964777492/tower-of-thje-corner"},
  {"id": 237, "abbr": "ToUC", "name": "Tower of Un Ca", "diff": 1144, "places": [["Place", ""]], "game": "https://www.roblox.com/games/9454260129/Tower-of-Un-Ca"},
  {"id": 238, "abbr": "ToTDTHL:SN", "name": "Tower of The Drive Towards Human Limits: Super Nerf", "diff": 1152, "places": [["ATS", "Ring 3"]]},
  {"id": 239, "abbr": "ToTWV", "name": "Tower of The Wedges Vengeance", "diff": 1168, "places": [["Place", "Ring 3"]], "game": "https://www.roblox.com/games/10196698433/Tower-of-The-Wedges-Vengeance"},
  {"id": 240, "abbr": "ToSA", "name": "Tower of Spatial Awareness", "diff": 1245, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10556896129/Tower-of-Spatial-Awareness"},
  {"id": 241, "abbr": "SoCB", "name": "Steeple of Cheese Burger", "diff": 1257, "places": [["JToH", "Pit of Misery"]]},
  {"id": 242, "abbr": "SoNB", "name": "Steeple of Nilly Bob", "diff": 1262, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 243, "abbr": "ToSR", "name": "Tower of Spiritual Rise", "diff": 1272, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 244, "abbr": "IT", "name": "Ikea Tower", "diff": 1307, "places": [["Place", ""]], "game": "https://www.roblox.com/games/17379816541/Sweden-Tower"},
  {"id": 245, "abbr": "WHT", "name": "Worlds Hardest Tower", "diff": 1007, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11561092817/Worlds-Hardest-Tower"},
  {"id": 246, "abbr": "ToRH", "name": "Tower of Raw Hotdog", "diff": 1009, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7576926901/the-hotdog-collection"},
  {"id": 247, "abbr": "ToAF", "name": "Tower of Anarchist Fantasies", "diff": 994, "places": [["Place", ""]], "game": "https://www.roblox.com/games/9808788974/Tower-of-Anarchist-Fantasies#!/game-instances"},
  {"id": 248, "abbr": "ToPP", "name": "Tower of Painful Poling", "diff": 998, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10806596789/when-the-pole"},
  {"id": 249, "abbr": "ToPR", "name": "Tower of Painful Rememberance", "diff": 979, "places": [["Place", ""]], "game": "https://www.roblox.com/games/6069627819/Tower-of-Painful-Remembrance"},
  {"id": 250, "abbr": "ToSC", "name": "Tower of Scattered Challenges", "diff": 1019, "places": [["Place", ""]], "game": "https://www.roblox.com/games/12194792902/Tower-of-Scattered-Challenges-Itemless"},
  {"id": 251, "abbr": "ToID", "name": "Tower of Indefinite Darkness", "diff": 1022, "places": [["Place", ""]], "game": "https://www.roblox.com/games/4899600584/Tower-of-Indefinite-Darkness"},
  {"id": 252, "abbr": "ToTLT", "name": "Tower of Two Layered Terror", "diff": 981, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15172639224/Tower-of-Two-Layered-Terror"},
  {"id": 253, "abbr": "ToAA", "name": "Tower of Architectural Agony", "diff": 1029, "places": [["Place", ""]], "game": "https://www.roblox.com/games/13419081799/ToAA-ToAL"},
  {"id": 254, "abbr": "ToSaPP", "name": "Tower of Specific and Precise Positioning", "diff": 1015, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11935897006/tower-of-specific-and-precise-positioning"},
  {"id": 255, "abbr": "ToMEN", "name": "Tower of Melodramatic Esoteric Nebulosity", "diff": 1031, "places": [["Place", ""]], "game": "https://www.roblox.com/games/12951065800/ToMEN"},
  {"id": 256, "abbr": "ToQQ", "name": "Tower of Quantum Quadrivium", "diff": 1033, "places": [["JToH", "The Eternal Abyss"]]},
  {"id": 257, "abbr": "ToIH", "name": "Tower of Itetsuku Hoshi", "diff": 1012, "places": [["Place", ""]], "game": "https://www.roblox.com/games/5947459409/toih"},
  {"id": 258, "abbr": "ToAG", "name": "Tower of Atomical Geometry", "diff": 1045, "places": [["Place", ""]], "game": "https://www.roblox.com/games/8881431098/Tower-of-Atomical-Geometry"},
  {"id": 259, "abbr": "ToTMS", "name": "Tower of The Mewing Sigma", "diff": 1046, "places": [["Place", ""]], "game": "https://www.roblox.com/games/16709893629/Tower-of-the-Mewing-Sigma"},
  {"id": 260, "abbr": "ToPPP", "name": "Tower of Precariously Positioned Platforms", "diff": 1070, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10275687443/Tower-of-Precariously-Positioned-Platforms#!/about"},
  {"id": 261, "abbr": "ToHaHA", "name": "Tower of Hitbox and Health Abuse", "diff": 1061, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10066307934/Tower-of-Hitbox-and-Health-Abuse-Reborn"},
  {"id": 262, "abbr": "ToPP", "name": "Tower of Punishing Paroxysm", "diff": 1047, "places": [["Place", ""]], "game": "https://www.roblox.com/games/14981138060/ToPP-cscd#!/game-instances"},
  {"id": 263, "abbr": "SoWO", "name": "Steeple of Wacky Obstructions", "diff": 1050, "places": [["Place", ""]], "game": "https://www.roblox.com/games/14711169611/Steeple-of-wacky-obstructions"},
  {"id": 264, "abbr": "ToD", "name": "Tower of Duality", "diff": 1056, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7464196072/Tower-of-Duality"},
  {"id": 265, "abbr": "ToEP", "name": "Tower of Ethereal Punishment", "diff": 1065, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7416416909/Tower-of-Etherial-Punishment"},
  {"id": 266, "abbr": "ToCCCC", "name": "Tower of Complex Colossal Crossroad Climbing", "diff": 1066, "places": [["Place", ""]], "game": "https://www.roblox.com/games/17470232943/Tower-of-Complex-Colossal-Crossroad-Climbing"},
  {"id": 267, "abbr": "ToBM", "name": "Tower of Brisk Movement", "diff": 1071, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15280041135/Tower-of-Brisk-Movement"},
  {"id": 268, "abbr": "ToDP", "name": "Tower of Dynamic Pulse", "diff": 1041, "places": [["Place", ""]], "game": "https://www.roblox.com/games/14538880811/Tower-of-Dynamic-Pulse"},
  {"id": 269, "abbr": "ToRI", "name": "Tower of Reflecting Impediments", "diff": 1073, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15496896527/Tower-of-Reflecting-Impediments#!/game-instances"},
  {"id": 270, "abbr": "ToRRR", "name": "Tower of Roughly Rotated Ruin", "diff": 1075, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7676098737/tower-of-roughly-rotated-ruin-redone"},
  {"id": 271, "abbr": "ToTOB", "name": "Tower of The Opp Block", "diff": 1087, "places": [["Place", ""]], "game": "https://www.roblox.com/games/17132742641/tower-of-the-opp-block"},
  {"id": 272, "abbr": "ToID", "name": "Tower of Interstellar Division", "diff": 1093, "places": [["Place", ""]], "game": "https://www.roblox.com/games/9601383628/tower-of-interstellar-division"},
  {"id": 273, "abbr": "ToHC", "name": "Tower of Hoarse Constraints", "diff": 1034, "places": [["Place", ""]], "game": "https://www.roblox.com/games/12638736665/Tower-of-Hoarse-Constraints"},
  {"id": 274, "abbr": "ToQM", "name": "Tower of Quantum Mentality", "diff": 1081, "places": [["ZToA", "Regret's Cave"]]},
  {"id": 275, "abbr": "ToDP", "name": "Tower of Destructive Peril", "diff": 1083, "places": [["TBP", "Plate 10"]]},
  {"id": 276, "abbr": "ToNI", "name": "Tower of Narrow Intensification", "diff": 1094, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15293301930/Tower-of-Narrow-Intensification"},
  {"id": 277, "abbr": "ToHI", "name": "Tower of Heinous Interference", "diff": 1085, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7260155319/Tower-of-Heinous-Interference"},
  {"id": 278, "abbr": "ToFT", "name": "Tower of Flummin' Time", "diff": 1090, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15330982496/Tower-of-Flummin-Time#!/game-instances"},
  {"id": 279, "abbr": "ToCS", "name": "Tower of Circuitous Spiral", "diff": 1078, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10913079814/Tower-of-Circuitous-Spiral"},
  {"id": 280, "abbr": "ToRI", "name": "Tower of Radioactive Inclusions", "diff": 1059, "places": [["Place", ""]], "game": "https://www.roblox.com/games/15496896527/Tower-of-Reflecting-Impediments#!/game-instances"},
  {"id": 281, "abbr": "ToHaD", "name": "Tower of Hell and Despair", "diff": 1078, "places": [["Place", ""]], "game": "https://www.roblox.com/games/5549397467/ring-2000#!/game-instances"},
  {"id": 282, "abbr": "ToCUP", "name": "Tower of Cruel Underestimated Parkour", "diff": 1090, "places": [["Place", ""]], "game": "https://www.roblox.com/games/6378913844/a-sequel-to-some-tower-ToCUP"},
  {"id": 283, "abbr": "ToPT", "name": "Tower of Precise Turns", "diff": 1114, "places": [["Place", ""]], "game": "https://roblox.com/games/10260790188/tower-of-precise-turns"},
  {"id": 284, "abbr": "ToYH", "name": "Tower of Yummy Hotdog", "diff": 1095, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7576926901/the-hotdog-collection"},
  {"id": 285, "abbr": "ToATC", "name": "Tower of Atrocious Truss Catastrophe", "diff": 1097, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10197956443/ToATC-OLD"},
  {"id": 286, "abbr": "ToPT", "name": "Tower of Perplexed Ascent", "diff": 1098, "places": [["Place", ""]], "game": "https://www.roblox.com/games/14477908828/Tower-of-Perplexed-Ascent-Fixed"},
  {"id": 287, "abbr": "SoWTT", "name": "Steeple of World's Tightest Timer", "diff": 1108, "places": [["Place", ""]], "game": "https://www.roblox.com/games/17549288909/steeple-of-the-worlds-tightest-timer"},
  {"id": 288, "abbr": "ToLLL", "name": "Tower of Long Lasting Leukophobia", "diff": 1105, "places": [["Place", ""]], "game": "https://www.roblox.com/games/7275802168/Tower-of-Long-Lasting-Leukophobia-V1"},
  {"id": 289, "abbr": "ToDS", "name": "Tower of Decaying Serenity", "diff": 1106, "places": [["Place", ""]], "game": "https://www.roblox.com/games/11987886595/Tower-of-Decaying-Serenity"},
  {"id": 290, "abbr": "ToCG", "name": "Tower of Champion's Gaming", "diff": 1091, "places": [["Place", ""]], "game": "https://www.roblox.com/games/10296461545/tower-of-champions-gaming-classic"},
  {"id": 291, "abbr": "ToTSC", "name": "Tower of The Seventh Chromosome", "diff": 1112, "places": [["Place", ""]], "game": "https://www.roblox.com/games/12723437565/Tower-of-The-Seventh-Chromosome"},
  {"id": 292, "abbr": "SoPA", "name": "Steeple of Pine Apple", "diff": 1113, "places": [["Place", ""]], "game": "https://www.roblox.com/games/14015694646/Steeple-of-Pine-Apple"},
]
